// at1.js : Activité-type 1 (front-end) : une compétence par exemple.
const AT1 = "Développer la partie front-end d'une application web ou web mobile sécurisée";

module.exports = [
  // ══════════════════════════════════════════════════════════════ CP 1
  {
    at: 1, atTitre: AT1, ex: 1,
    titre: "Installer et configurer son environnement de travail en fonction du projet web ou web mobile",
    cps: ['CP 1 : Installer et configurer son environnement de travail en fonction du projet web ou web mobile'],
    taches: [
      { t: 'h', v: 'Contexte du projet' },
      { t: 'p', v: "Kinka.fr est une boutique en ligne de vente de mangas neufs et d'occasion, développée comme projet fil rouge de ma formation de développeur web et web mobile. J'ai démarré ce projet en janvier 2026, après la phase de fondamentaux, et je l'ai mené jusqu'à mon départ en stage, en juin." },
      { t: 'p', v: "La première étape a consisté à installer et à configurer de zéro l'environnement de travail que j'ai ensuite utilisé pendant toute la durée du développement." },

      { t: 'h', v: "1) Serveur local, exécution et éditeur" },
      { t: 'p', v: "J'ai installé Laragon, qui fournit un serveur Apache et un serveur de données MySQL 8 en local, puis Node.js pour exécuter le serveur applicatif. J'ai retenu Visual Studio Code comme environnement de développement intégré, complété des extensions utiles au projet : coloration de la syntaxe SQL, client HTTP pour appeler l'API sans quitter l'éditeur, et Live Server pour servir les pages statiques." },
      { t: 'p', v: "J'ai vérifié chaque installation par sa commande de version avant de passer à la suivante, ce qui m'a évité de chercher plus tard l'origine d'une incompatibilité." },

      { t: 'h', v: '2) Gestion des versions et protection des identifiants' },
      { t: 'p', v: "Pour la gestion des versions et la collaboration, j'ai créé un dépôt Git local que j'ai relié à un dépôt distant sur GitHub. J'ai écrit le fichier .gitignore de manière à ce que les dépendances (node_modules) et surtout les fichiers de configuration contenant des identifiants (.env) ne soient jamais versionnés. J'ai versionné à la place un fichier .env.example documentant chaque variable attendue, sans valeur réelle." },
      { t: 'p', v: "Cette précaution s'est révélée insuffisante en fin de projet : un secret s'était glissé dans l'historique avant que le .gitignore ne soit complet. J'ai dû réécrire l'historique pour le purger et renouveler la valeur exposée. J'en ai retenu qu'un fichier ignoré protège les commits à venir, pas ceux déjà faits." },

      { t: 'h', v: '3) Outils de contrôle de la qualité du code' },
      { t: 'p', v: "J'ai mis en place ESLint 9 pour l'analyse statique et Prettier pour le formatage. La configuration ESLint distingue deux contextes, parce que le projet en contient deux : le front-end s'exécute dans le navigateur sous forme de scripts classiques partageant un même contexte global, tandis que l'API s'exécute sous Node en modules CommonJS. Une configuration unique aurait produit des centaines de faux positifs." },
      { t: 'code', caption: 'eslint.config.js : deux contextes dans une même configuration « flat »', lines: [
        "const js = require('@eslint/js');",
        "const globals = require('globals');",
        '',
        'module.exports = [',
        "  { ignores: ['**/node_modules/**'] },",
        '  js.configs.recommended,',
        '',
        '  // Front-end (navigateur, scripts globaux)',
        '  {',
        "    files: ['client/assets/js/**/*.js'],",
        "    languageOptions: { ecmaVersion: 2022, sourceType: 'script',",
        '                       globals: { ...globals.browser } },',
        '    rules: {',
        "      'no-undef': 'off',",
        "      'no-unused-vars': ['warn', { vars: 'local', args: 'none' }],",
        '    },',
        '  },',
        '',
        '  // Back-end (Node / CommonJS)',
        '  {',
        "    files: ['server/**/*.js'],",
        "    languageOptions: { ecmaVersion: 2022, sourceType: 'commonjs',",
        '                       globals: { ...globals.node } },',
        '  },',
        '];',
      ] },
      { t: 'p', v: "J'ai regroupé ces contrôles dans des commandes npm afin de pouvoir les lancer d'un seul appel, et j'ai ajouté un script de vérification que j'ai écrit moi-même : il parcourt les pages HTML et échoue si un script JavaScript est écrit directement dans la page. Ce contrôle m'obligeait à sortir tout le code dans des fichiers séparés, ce qui rend l'application compatible avec une politique de sécurité de contenu (CSP) stricte et évite de dupliquer du code de page en page." },
      { t: 'code', caption: "package.json : commandes de qualité et d'exploitation", lines: [
        '"scripts": {',
        '  "dev":          "nodemon server/src/server.js",',
        '  "start":        "node server/src/server.js",',
        '  "lint":         "eslint . && node server/scripts/check_inline_scripts.js",',
        '  "format":       "prettier --write .",',
        '  "format:check": "prettier --check .",',
        '  "seed:big":     "node server/scripts/seed_big.js",',
        '  "sync":         "node server/scripts/sync_mangas_jikan.js --pages 4"',
        '}',
      ] },

      { t: 'h', v: '4) Documentation technique et veille' },
      { t: 'p', v: "Toute la documentation technique des outils que j'ai installés a été consultée dans sa version d'origine : en anglais pour Node.js, Express, ESLint et le pilote mysql2, en français lorsqu'une traduction officielle existait, comme sur MDN." },
      { t: 'p', v: "J'ai mis en place une veille technologique reposant sur la documentation MDN, le blog de Node.js, le Top 10 de l'OWASP et les bulletins de l'ANSSI, afin de suivre les évolutions techniques et les problématiques de sécurité des technologies que j'utilise. C'est cette veille qui m'a fait découvrir la recommandation NIST sur les mots de passe, appliquée plus tard dans les composants métier." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Matériel : ordinateur portable personnel sous Windows 11.',
        'Environnements : Laragon (Apache, MySQL 8), Node.js 18, npm 9.',
        'Éditeur : Visual Studio Code et ses extensions SQL, client HTTP et Live Server.',
        'Versions : Git, dépôt distant GitHub, fichiers .gitignore et .env.example.',
        'Qualité du code : ESLint 9, Prettier 3, script de vérification écrit pour le projet.',
        "Documentation : sites officiels de Node.js, Express, ESLint et mysql2, consultés en anglais (niveau B1) ; MDN Web Docs en français.",
        "Veille : Top 10 de l'OWASP, bulletins de l'ANSSI, blog de Node.js.",
      ] },
    ],
    avecQui: [
      { t: 'p', v: "J'ai réalisé ce travail seul." },
      { t: 'p', v: "J'ai comparé mes choix d'outils avec ceux des autres stagiaires de ma promotion, ce qui m'a conduit à ajouter Prettier, que je n'avais pas prévu. Mon formateur a validé la configuration ESLint à deux contextes, qu'il a jugée plus lisible qu'une désactivation globale des règles gênantes." },
    ],
    periode: 'Du 05/01/2026 au 16/01/2026',
    infos: [
      { t: 'p', v: "Le script de vérification des scripts en ligne est le seul outil que j'ai écrit moi-même. Il tient en une trentaine de lignes, mais il a tenu la règle pendant dix mois là où ma seule discipline aurait fini par céder." },
      { t: 'p', v: "Sur le point de la conteneurisation : mon environnement repose sur une pile locale et non sur des conteneurs. J'ai étudié Docker pendant la formation et j'en connais l'intérêt pour reconstituer sur son poste un environnement conforme à celui de production. Ce projet, mono-poste et sans environnement partagé, ne le justifiait pas." },
    ],
  },

  // ══════════════════════════════════════════════════════════════ CP 2
  {
    at: 1, atTitre: AT1, ex: 2,
    titre: 'Maquetter des interfaces utilisateur web ou web mobile',
    cps: ['CP 2 : Maquetter des interfaces utilisateur web ou web mobile'],
    taches: [
      { t: 'p', v: "Le maquettage s'est appuyé sur un cahier des charges que j'ai rédigé au préalable, puis sur l'arborescence du site et le schéma d'enchaînement des écrans. J'ai ensuite construit un design system, dessiné les wireframes de toutes les pages, et décliné chaque écran en maquette haute fidélité." },

      { t: 'h', v: '1) Le cahier des charges' },
      { t: 'p', v: "Le marché du manga en France est le deuxième au monde après le Japon, mais l'offre en ligne est dominée par des enseignes généralistes où le manga n'est qu'un rayon parmi d'autres. Deux manques reviennent chez les lecteurs : la difficulté à retrouver un tome précis dans une série longue, dont certaines dépassent cent volumes, et l'absence de circuit fiable pour revendre les tomes déjà lus." },
      { t: 'p', v: "J'ai traduit ce constat en trois problèmes à résoudre, qui ont ensuite gouverné toutes mes décisions de conception. Un lecteur qui suit une série veut acheter « le tome 47 », pas « un manga » : la navigation doit donc partir de la série et pas seulement du catalogue global. Sur l'occasion, l'acheteur ne peut pas manipuler le livre, il doit donc voir son état, une photo réelle et le vendeur. Enfin, un catalogue de plus de 3 000 références devient inutilisable sans filtres efficaces et sans recherche rapide." },
      { t: 'p', v: "J'ai ensuite fixé six objectifs, chacun associé à une mesure. Sans mesure, on ne sait pas si l'objectif est atteint ; ces mesures m'ont servi de critères de recette en fin de projet." },
      { t: 'tab',
        entetes: ['Objectif', "Ce qu'il impose", 'Mesure retenue'],
        largeurs: [2100, 4560, 2700], premiereGras: true,
        lignes: [
          ['Trouver vite', "Atteindre une fiche produit en trois clics au maximum depuis l'accueil", 'Profondeur de navigation inférieure ou égale à 3'],
          ['Ne pas perdre le panier', 'Un panier constitué hors connexion doit survivre à la connexion', 'Taux de perte de panier : 0 %'],
          ['Ne jamais survendre', 'Aucune commande ne doit dépasser le stock disponible', 'Stock négatif : 0 occurrence'],
          ['Rester utilisable sur mobile', 'Tous les parcours doivent aboutir à 390 pixels de large', '100 % des parcours testés'],
          ['Rester accessible', 'Contrastes conformes au niveau AA sur les deux thèmes', 'Rapport supérieur ou égal à 4,5:1 sur le texte'],
          ['Rester autonome', 'La boutique se gère sans intervention sur le code', '0 modification de code pour une tâche courante'],
        ],
        legende: 'Cahier des charges : objectifs et indicateurs associés.' },
      { t: 'p', v: "J'ai également écrit ce qui était hors périmètre, et pourquoi : une limite écrite est une décision, une limite tue est un oubli. Le paiement bancaire réel en fait partie, la conformité PCI-DSS dépassant le cadre du projet ; l'étape existe et crée la commande, mais aucune donnée bancaire ne circule. Sont aussi exclus la gestion effective des retours et remboursements, la facturation comptable, et le prélèvement de l'abonnement dont l'interface existe sans le débit." },
      { t: 'pic', file: '02_cahier_des_charges/01_contexte_objectifs.png', w: 600,
        caption: "Cahier des charges : contexte, problème à résoudre, objectifs mesurables et hors-périmètre assumé." },

      { t: 'p', v: "J'ai construit quatre personas à partir des usages réels que le site devait servir, plutôt que des profils décoratifs : chacun a tranché au moins une décision de conception. Léa, collectionneuse qui suit six séries et navigue à 80 % sur mobile, a imposé la fiche série et l'affichage du stock réel. Thomas, néophyte qui veut offrir un manga sans rien y connaître, a imposé les sélections éditoriales de l'accueil. Karim, revendeur, a imposé un formulaire d'annonce court, car il abandonne au-delà de deux minutes. Camille, gérante de la boutique et non développeuse, a imposé l'existence du back-office." },
      { t: 'pic', file: '02_cahier_des_charges/02_personas.png', w: 580,
        caption: "Cahier des charges : les quatre personas, ce qu'ils cherchent, ce qui les bloque, et ce que chacun a tranché." },

      { t: 'p', v: "J'ai formalisé les besoins en vingt-quatre user stories réparties en cinq épopées, hiérarchisées par la méthode MoSCoW. Cette hiérarchisation m'a servi à arbitrer quand le temps a manqué : les « Must » ont tous été livrés, deux « Could » ont été abandonnés en cours de route sans que le site en pâtisse." },
      { t: 'tab',
        entetes: ['Priorité', 'Épopée', 'Exemples de besoins exprimés'],
        largeurs: [1500, 2400, 5460], premiereGras: true,
        lignes: [
          ['Must', 'Parcourir le catalogue', "Parcourir par catégorie, éditeur et série ; filtrer par état, prix et disponibilité ; rechercher avec des suggestions au fil de la frappe"],
          ['Must', 'Acheter', "Ajouter au panier sans créer de compte ; retrouver son panier après connexion ; être empêché de commander plus que le stock ; recevoir un numéro de commande lisible"],
          ['Must', 'Gérer mon compte', "Créer un compte avec un mot de passe robuste ; confirmer son adresse par un lien reçu par email ; réinitialiser son mot de passe"],
          ['Must', 'Administrer', "Modifier prix et stock depuis une interface ; changer le statut d'une commande et saisir le suivi"],
          ['Should', 'Revendre et participer', "Déposer une annonce d'occasion en quelques champs ; ne modifier que ses propres annonces ; supprimer son compte et toutes ses données"],
          ['Could', 'Confort', "Consulter la fiche d'une série et l'ordre de ses tomes ; noter et commenter un produit ; enregistrer des favoris"],
          ["Won't", 'Hors périmètre', "Payer réellement par carte bancaire, la conformité PCI-DSS dépassant le cadre du projet"],
        ],
        legende: 'Cahier des charges : les 24 user stories hiérarchisées par la méthode MoSCoW, extrait par priorité.' },
      { t: 'p', v: "J'ai enfin posé quatre exigences non négociables, qui s'appliquent à tous les écrans sans exception. Chaque écran doit rester utilisable à 390 pixels de large. Les contrastes doivent être vérifiés au seuil WCAG AA et la navigation possible au clavier. Le thème sombre est obligatoire et respecte par défaut la préférence du système. Aucune bibliothèque d'interface externe n'est admise, pour que le poids des pages reste maîtrisé." },
      { t: 'saut' },

      { t: 'h', v: "2) Arborescence du site et enchaînement des écrans" },
      { t: 'p', v: "J'ai formalisé l'arborescence du site afin de définir les pages à produire et les chemins de navigation. Je l'ai organisée en cinq zones, parce que c'est la zone qui conditionne l'accès : public, achat, espace membre, service et légal, back-office. Le site compte 43 pages, dont trois ne sont que des redirections conservées pour ne pas casser les liens et favoris existants." },
      { t: 'pic', file: '02_cahier_des_charges/10_arborescence.png', w: 620,
        caption: "Arborescence du site : les 43 pages réparties en cinq zones d'accès." },
      { t: 'p', v: "J'ai ensuite formalisé l'enchaînement des écrans par un schéma. Il montre le parcours d'achat nominal en sept écrans, mais surtout les bifurcations, c'est-à-dire les écrans atteints depuis une condition et non depuis un lien de navigation. Ce sont ces bifurcations qui font les défauts d'un site, et les écrire avant de coder m'a évité d'en découvrir en production." },
      { t: 'p', v: "Le schéma fixe aussi les quatre états à dessiner sur chaque écran : chargement, vide, erreur, succès. Un état oublié en maquette devient un écran blanc en production. C'est la raison pour laquelle j'ai maquetté séparément l'état vide des favoris et l'état « accès refusé » de l'espace membre." },
      { t: 'pic', file: '02_cahier_des_charges/11_enchainement.png', w: 620,
        caption: "Enchaînement des écrans : parcours nominal, huit bifurcations avec leur condition, et les quatre états à dessiner." },
      { t: 'saut' },

      { t: 'h', v: '3) Le design system' },
      { t: 'p', v: "Avant de dessiner les écrans, j'ai construit un design system : palette de couleurs, typographie, échelle de tailles, rayons de bordure, ombres, et composants réutilisables avec leurs états. Chaque couleur y est documentée par son nom de variable CSS, sa valeur hexadécimale, son usage et son contraste mesuré." },
      { t: 'p', v: "C'est à cette occasion que j'ai découvert que le rose de la charte ne tenait pas le seuil d'accessibilité, ce qui m'a conduit à en décliner deux variantes selon l'usage ; le détail figure à l'exemple suivant. Le fait d'avoir mesuré les contrastes au moment du design system, et non après l'intégration, m'a évité de reprendre quarante écrans." },
      { t: 'duo', caption: 'Design system : palette documentée avec contrastes mesurés, et bibliothèque de composants avec leurs états.',
        files: [
          { file: '01_design_system/01_couleurs.png', w: 300 },
          { file: '01_design_system/03_composants.png', w: 300 },
        ] },
      { t: 'saut' },

      { t: 'h', v: '4) Les wireframes, page par page' },
      { t: 'p', v: "J'ai réalisé les wireframes en basse fidélité, sous forme de schémas en nuances de gris qui décrivent la structure sans traiter l'apparence. Cette étape m'a obligé à trancher les questions de hiérarchie de l'information avant de me préoccuper de l'esthétique." },
      { t: 'p', v: "J'ai couvert la totalité du site, et non les seuls écrans principaux. Trois des 43 pages sont de simples redirections sans interface. Parmi les 40 restantes, la page d'administration porte neuf sections derrière des onglets, chacune étant un écran à part entière, et deux pages ont un second état à dessiner : les favoris quand la liste est vide, et l'espace membre quand l'accès est refusé. Le décompte s'établit donc ainsi :" },
      { t: 'tab',
        entetes: ['Décompte', 'Nombre'],
        largeurs: [7000, 2360], premiereGras: true,
        lignes: [
          ['Pages HTML du site', '43'],
          ['dont redirections sans interface (page_categorie, page_produit, page_oda)', '− 3'],
          ['page_admin.html éclatée en ses neuf sections', '− 1 + 9'],
          ['états supplémentaires (favoris vide, compte sans accès)', '+ 2'],
          ['Écrans à maquetter', '50'],
          ['Cadres produits : chaque écran en wireframe et en maquette, bureau et mobile', '200'],
        ],
        legende: "Du fichier HTML à l'écran : le décompte est vérifiable page par page dans la table de correspondance." },
      { t: 'p', v: "Chaque écran existe en deux formats, bureau à 1440 pixels et mobile à 390 pixels. Chaque cadre porte en pied le nom du fichier HTML auquel il correspond, ce qui rend le lien entre la conception et le site livré vérifiable écran par écran. Les wireframes portent en outre des zones annotées et des encadrés « NOTE » qui consignent les décisions prises et leur raison." },
      { t: 'duo', caption: "Wireframes du catalogue, versions bureau (1440 px) et mobile (390 px). Les zones annotées et l'encadré « NOTE » consignent les décisions de conception.",
        files: [
          { file: '03_wireframes/bureau/02_catalogue.png', w: 430 },
          { file: '03_wireframes/mobile/02_catalogue.png', w: 122 },
        ] },
      { t: 'pic', file: '03_wireframes/00_correspondance.png', w: 470,
        caption: "Table de correspondance : une ligne par page du site, avec l'écran qui la couvre. Les redirections y figurent pour que le décompte des 43 pages reste vérifiable." },
      { t: 'saut' },

      { t: 'h', v: '5) Les maquettes haute fidélité' },
      { t: 'p', v: "J'ai décliné chacun des 50 écrans en maquette haute fidélité, en bureau et en mobile, en reprenant les couleurs, rayons, graisses et espacements réels du design system. Les écrans les plus structurants ont en outre été maquettés en thème sombre, pour vérifier que le basculement ne cassait ni la lisibilité ni la hiérarchie visuelle." },
      { t: 'duo', caption: "Maquette de l'accueil en thème clair et en thème sombre. Seules les valeurs des variables changent : aucune règle de style n'est dupliquée.",
        files: [
          { file: '04_maquettes/bureau/01_accueil.png', w: 296 },
          { file: '04_maquettes/bureau/01_accueil_sombre.png', w: 296 },
        ] },
      { t: 'duo', caption: "Maquette de la fiche produit en bureau, et de l'accueil en mobile : la grille passe de cinq à deux colonnes, les filtres se replient, l'action principale occupe toute la largeur.",
        files: [
          { file: '04_maquettes/bureau/03_fiche_produit.png', w: 430 },
          { file: '04_maquettes/mobile/01_accueil.png', w: 118 },
        ] },
      { t: 'p', v: "Les écrans ne sont pas dessinés un par un : ils sont décrits une seule fois dans un fichier de description, dont un moteur de rendu tire les quatre déclinaisons. Cette organisation garantit qu'un écran ne peut pas exister en wireframe sans exister aussi en maquette, en bureau comme en mobile, et rend la reprise d'une décision de charte immédiate sur les 200 cadres." },

      { t: 'h', v: "6) Accessibilité et éco-conception, prises en compte dès la maquette" },
      { t: 'p', v: "Dès le maquettage, j'ai pris en compte l'expérience de l'utilisateur en situation de handicap, en me référant au référentiel général d'amélioration de l'accessibilité (RGAA) : contraste suffisant entre le texte et le fond, taille minimale des zones cliquables, information jamais portée par la seule couleur, ordre de lecture cohérent, et libellés explicites sur les champs de formulaire plutôt que de simples textes d'aide placés à l'intérieur des champs." },
      { t: 'p', v: "J'ai également identifié les besoins d'éco-conception à ce stade, car ce sont des choix de maquette autant que de code : renoncer aux polices décoratives lourdes et aux animations permanentes, limiter le nombre d'images par écran, prévoir un chargement progressif du catalogue plutôt qu'un défilement infini qui télécharge des données que l'utilisateur ne consultera pas." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Outil de maquettage : Figma, formats bureau 1440 px et mobile 390 px.',
        "Méthode : cahier des charges (contexte, objectifs mesurables, personas, user stories MoSCoW), arborescence, schéma d'enchaînement, wireframes puis maquettes.",
        'Référentiels : RGAA et WCAG 2.1 niveau AA, référentiel général d\'éco-conception des services numériques (RGESN).',
        'Vérification : outil de mesure de contraste appliqué à chaque couple de couleurs de la palette.',
        'Livrables : 200 cadres d\'écran, 17 planches de cahier des charges et de conception des données, 3 planches de design system.',
      ] },
    ],
    avecQui: [
      { t: 'p', v: "J'ai réalisé ce travail seul." },
      { t: 'p', v: "J'ai présenté le cahier des charges, l'arborescence, le schéma d'enchaînement et les maquettes à mon formateur, qui m'a fait des retours sur la hiérarchie de l'information et la cohérence des parcours. C'est à sa demande que j'ai associé une mesure à chacun des six objectifs : ma première version les énonçait sans moyen de les vérifier. J'ai également fait relire les maquettes par deux stagiaires de ma promotion." },
    ],
    periode: 'Du 19/01/2026 au 13/02/2026',
    infos: [
      { t: 'p', v: "Le fait de passer par des wireframes avant les maquettes m'a évité de refaire trois fois la page catalogue : les questions de structure, où placer les filtres et combien de colonnes afficher, étaient déjà tranchées quand j'ai abordé la couleur." },
      { t: 'p', v: "Ma première version des wireframes mutualisait des pages que je croyais identiques : les promotions, les coups de cœur, l'occasion et les quatre catégories partageaient un seul gabarit. En reprenant le site page par page, j'ai constaté que chacune portait en réalité son propre en-tête, ses propres chiffres et sa propre couleur d'accent. Je les ai donc maquettées séparément. C'est ce qui m'a appris à inventorier avant de mutualiser, et non l'inverse." },
    ],
  },

  // ══════════════════════════════════════════════════════════════ CP 3
  {
    at: 1, atTitre: AT1, ex: 3,
    titre: 'Réaliser des interfaces utilisateur statiques web ou web mobile',
    cps: ['CP 3 : Réaliser des interfaces utilisateur statiques web ou web mobile'],
    taches: [
      { t: 'p', v: "Après validation des maquettes, j'ai intégré les interfaces en HTML et CSS, sans utiliser de framework, afin de garder la maîtrise complète du rendu et de limiter le poids des pages." },
      { t: 'h', v: '1) Structure sémantique et référencement' },
      { t: 'p', v: "J'ai structuré chaque page avec des balises sémantiques, header, nav, main, section, article et footer, plutôt qu'avec des divisions génériques, afin que la page reste compréhensible par un lecteur d'écran comme par un moteur de recherche. J'ai produit 43 pages : accueil, catalogue, fiche produit, panier, tunnel de commande, espace client, pages de catégories, pages d'éditeurs, pages légales et back-office." },
      { t: 'p', v: "Pour le référencement, chaque page porte un titre et une méta-description qui lui sont propres et décrivent son contenu réel, ainsi qu'une hiérarchie de titres à un seul h1. Les images de couverture portent un texte alternatif construit à partir du titre de l'ouvrage." },
      { t: 'code', caption: 'client/pages/page_accueil.html : en-tête de page', lines: [
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<meta name="description" content="KINKA.FR, votre boutique manga en ligne :',
        '      neufs, occasions, coffrets, exclusivités.">',
        '<title>KINKA.FR - Votre boutique manga de référence</title>',
      ] },
      { t: 'h', v: '2) Mise en page adaptable (responsive)' },
      { t: 'p', v: "Pour la mise en page, j'ai utilisé Flexbox et CSS Grid, en travaillant d'abord la version mobile puis en élargissant. J'ai retenu trois points de rupture, correspondant aux usages réels et non à des modèles d'appareils. En dessous de 768 pixels, la grille de produits passe à deux colonnes et les filtres se replient derrière un bouton. Entre 768 et 1200 pixels, elle passe à trois ou quatre colonnes. Au-delà, cinq colonnes avec les filtres affichés en permanence." },
      { t: 'duo', caption: "Le catalogue en bureau et en mobile : la grille passe de cinq à deux colonnes et le panneau de filtres devient un bouton « Filtrer et trier ».",
        files: [
          { file: '04_maquettes/bureau/02_catalogue.png', w: 430 },
          { file: '04_maquettes/mobile/02_catalogue.png', w: 118 },
        ] },
      { t: 'h', v: '3) Thème sombre par variables CSS' },
      { t: 'p', v: "J'ai centralisé toutes les couleurs, les rayons et les ombres dans des variables CSS. Cela m'a permis d'ajouter un thème sombre complet sans dupliquer une seule règle de style : seules les valeurs des variables changent. Le thème respecte par défaut la préférence exprimée par le système d'exploitation, puis mémorise le choix explicite de l'utilisateur." },
      { t: 'p', v: "La première version présentait un défaut visible. La feuille du thème sombre étant appliquée par un script chargé en fin de page, chaque navigation produisait un éclair blanc avant le basculement. Je l'ai corrigé par un très court script placé dans l'en-tête, qui pose une classe sur l'élément racine avant le premier rendu." },
      { t: 'code', caption: 'client/assets/css/darkmode.css : variables du thème et suppression du flash', lines: [
        '/* Fond sombre appliqué avant le premier rendu, pour supprimer',
        "   l'éclair blanc à chaque navigation. */",
        'html.pre-dark-mode,',
        'html.pre-dark-mode body { background: #0f1117; color: #f0f0f0; }',
        '',
        'body.dark-mode {',
        '  --text:       #f0f0f0;',
        '  --text-muted: #a0a8b4;',
        '  /* #6b7280 tombait à 3,30:1 sur les cartes sombres, sous le',
        '     minimum WCAG AA de 4,5:1. #8a92a1 tient 5,10:1 au pire des',
        '     fonds sombres, en restant le même gris neutre. */',
        '  --text-light: #8a92a1;',
        '  --bg:         #0f1117;',
        '  --bg-card:    #1a1d27;',
        '}',
      ] },
      { t: 'h', v: '4) Accessibilité' },
      { t: 'p', v: "J'ai traité l'accessibilité tout au long de l'intégration, en suivant le RGAA : attributs ARIA sur les éléments interactifs, textes alternatifs sur les images, navigation complète au clavier avec un ordre de tabulation cohérent et un indicateur de focus visible, libellés associés à chaque champ de formulaire." },
      { t: 'p', v: "J'ai vérifié les contrastes avec un outil de mesure plutôt qu'à l'œil, et le résultat m'a surpris. Le rose de la charte, #e03b8b, ne tient que 3,69:1 lorsqu'il sert de couleur de texte et 4,06:1 en aplat sous du texte blanc, là où le niveau AA exige 4,5:1. J'ai donc décliné deux variantes selon l'usage : #c62372 quand le rose est le texte, à 4,90:1, et #d12d7d quand il porte du texte blanc, à 4,79:1. J'ai corrigé de la même façon trois gris secondaires, dont l'un ne mesurait que 2,54:1." },
      { t: 'p', v: "Plutôt que de reprendre à la main les seules couleurs repérées à l'écran, j'ai extrait les sélecteurs concernés depuis l'ensemble des feuilles du projet et rassemblé les corrections dans deux fichiers dédiés, l'un pour le thème clair et l'autre pour le thème sombre, chargés après les autres feuilles. La correction couvre ainsi tous les usages, et pas seulement ceux que j'avais vus." },
      { t: 'h', v: '5) Éco-conception et vérification' },
      { t: 'p', v: "Le site n'embarque aucun framework CSS ni aucune bibliothèque JavaScript tierce : le poids transféré se limite aux feuilles du projet et aux images du catalogue, elles-mêmes chargées à la demande. J'ai vérifié le résultat sur les deux thèmes, aux trois points de rupture, au clavier seul, et j'ai fait tester la navigation sur des téléphones réels." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Langages : HTML5, CSS3 (Flexbox, Grid, variables personnalisées, requêtes média).',
        'Outils : Visual Studio Code, outils de développement de Chrome et Firefox, Figma comme référence des maquettes, Git pour le versionnement.',
        'Vérification : outil de mesure de contraste, test manuel de la navigation au clavier, mode appareil mobile du navigateur, tests sur téléphones réels.',
        'Documentation : MDN Web Docs en anglais, référentiel RGAA, WCAG 2.1 niveau AA.',
      ] },
    ],
    avecQui: [
      { t: 'p', v: 'Travail réalisé seul.' },
      { t: 'p', v: "Mon formateur a relu l'intégration et m'a alerté sur des contrastes insuffisants, ce qui m'a conduit à reprendre la palette. J'ai également fait tester la navigation par deux stagiaires de ma promotion sur leurs propres téléphones." },
    ],
    periode: 'Du 03/03/2026 au 27/03/2026',
    infos: [
      { t: 'p', v: "L'intégration représente environ 20 000 lignes de CSS pour 43 pages. La difficulté principale a été de garder la cohérence visuelle sur autant d'écrans : je l'ai résolue en extrayant les composants récurrents, carte produit, badge, bouton et champ de formulaire, et en les documentant dans le design system." },
      { t: 'p', v: "Ce travail sur les contrastes m'a appris que l'accessibilité se mesure avec un outil et ne s'estime pas à l'œil : la couleur de marque du site, que personne n'avait remise en question, faisait partie des non-conformités." },
    ],
  },

  // ══════════════════════════════════════════════════════════════ CP 4
  {
    at: 1, atTitre: AT1, ex: 4,
    titre: 'Développer la partie dynamique des interfaces utilisateur web ou web mobile',
    cps: ['CP 4 : Développer la partie dynamique des interfaces utilisateur web ou web mobile'],
    taches: [
      { t: 'p', v: "J'ai rendu les interfaces dynamiques en JavaScript natif, en les connectant à l'API que j'avais développée." },
      { t: 'h', v: '1) Un client API centralisé' },
      { t: 'p', v: "J'ai d'abord écrit un client API centralisé : un module unique qui préfixe l'adresse de l'API, ajoute automatiquement le jeton d'authentification dans l'en-tête des requêtes protégées, et normalise le traitement des erreurs, y compris l'indisponibilité du réseau. Aucune page n'appelle le réseau directement." },
      { t: 'p', v: "Ce choix m'a permis, plus tard, de traiter en un seul endroit le cas du jeton expiré : lorsque l'API répond 401 alors qu'un jeton était présent, la session locale est purgée et l'utilisateur est renvoyé vers la page de connexion. Sans ce point unique, il aurait fallu répéter ce traitement dans chaque page." },
      { t: 'code', caption: 'client/assets/js/kinka-api-client.js : appel réseau centralisé', lines: [
        'async function kinkaFetchEnveloppe(path, options = {}) {',
        '  const token = KinkaAuth.getToken();',
        '  let res;',
        '  try {',
        '    res = await fetch(API + path, {',
        '      headers: {',
        "        'Content-Type': 'application/json',",
        '        ...(token ? { Authorization: `Bearer ${token}` } : {}),',
        '        ...options.headers',
        '      },',
        '      ...options',
        '    });',
        '  } catch (e) {',
        '    // Erreur réseau : API injoignable, CORS, etc.',
        "    throw new Error('Impossible de joindre le serveur.');",
        '  }',
        '  // Jeton rejeté : purge de la session en un seul point du code.',
        '  if (res.status === 401 && token) { KinkaAuth.removeToken(); ... }',
        '}',
      ] },
      { t: 'h', v: '2) Catalogue dynamique et prévention des injections' },
      { t: 'p', v: "J'ai développé l'affichage dynamique du catalogue : les fiches sont demandées à l'API avec les filtres actifs, puis les cartes produit sont construites par le code. Je n'insère jamais une donnée venant de la base avec innerHTML : j'utilise createElement et textContent, qui n'interprètent pas le HTML, afin qu'un titre contenant des balises ne puisse pas injecter de code dans la page. Cette règle est rendue systématique par le script de vérification décrit à l'exemple n° 1, qui interdit par ailleurs le JavaScript écrit directement dans les pages." },
      { t: 'p', v: "J'ai implémenté les filtres, le tri et la pagination en laissant la base de données faire le travail. Transmettre plus de 3 000 fiches au navigateur pour n'en afficher que vingt aurait été inefficace, en bande passante comme en mémoire, et contraire aux principes d'éco-conception." },
      { t: 'h', v: '3) Recherche avec autocomplétion' },
      { t: 'p', v: "J'ai développé la recherche avec autocomplétion. Les suggestions apparaissent au fil de la frappe à partir de deux caractères, avec une temporisation de 220 millisecondes qui évite de déclencher une requête à chaque touche : sur une recherche de dix caractères, cela ramène une dizaine d'appels à un ou deux. La liste est navigable au clavier et les résultats sont classés, les correspondances sur le titre passant avant celles sur la série." },
      { t: 'code', caption: 'client/assets/js/recherche.js : temporisation de la saisie', lines: [
        'var timer = null;',
        '',
        "input.addEventListener('input', function () {",
        '  clearTimeout(timer);',
        '  timer = setTimeout(function () {',
        '    show(input.value.trim());',
        '  }, 220);                    // temporisation : 220 ms',
        '});',
      ] },
      { t: 'pic', file: '04_maquettes/bureau/04_recherche.png', w: 560,
        caption: "Page de résultats de recherche : filtres à gauche, classement par pertinence, pagination, le tout exécuté côté base." },
      { t: 'h', v: '4) Panier hybride et fusion à la connexion' },
      { t: 'p', v: "J'ai développé le panier en mode hybride : conservé dans le navigateur pour un visiteur, enregistré en base pour un client connecté. En déroulant le parcours complet, j'ai découvert qu'un visiteur qui remplissait son panier puis se connectait le perdait entièrement. J'ai ajouté une fonction de fusion appelée juste après une connexion ou une inscription réussie : chaque article du panier local est poussé vers l'API, puis le panier local est vidé." },
      { t: 'code', caption: 'client/assets/js/authentification.js : fusion du panier invité', lines: [
        '// À appeler juste après une connexion/inscription réussie : pousse',
        "// chaque article du panier invité vers l'API puis vide le localStorage,",
        "// pour qu'un visiteur ne perde pas son panier en se connectant.",
        'async function fusionnerPanierInvite() {',
        '  let local = [];',
        "  try { local = JSON.parse(localStorage.getItem('kinka_panier') || '[]'); }",
        '  catch (_) { local = []; }',
        '  if (!Array.isArray(local) || !local.length) return;',
        '  for (const item of local) {',
        '    if (!item || !item.id) continue;',
        '    try { await KinkaAPI.panier.add(item.id, item.quantite || 1); }',
        '    catch (_) { /* stock ou plafond atteint : on ignore */ }',
        '  }',
        "  localStorage.removeItem('kinka_panier');",
        '}',
      ] },
      { t: 'pic', file: '04_maquettes/bureau/22_panier.png', w: 560,
        caption: "Le panier, quatrième étape du parcours. L'objectif « taux de perte de panier : 0 % » fixé au cahier des charges est ce qui a imposé la fusion à la connexion." },
      { t: 'h', v: "5) Qualité du code et jeu d'essai" },
      { t: 'p', v: "L'ensemble du code est commenté en français, ligne à ligne pour les parties délicates, et vérifié par ESLint avant chaque livraison. J'ai construit un jeu d'essai fonctionnel de douze cas couvrant le parcours d'achat, dont huit cas d'erreur provoqués volontairement, avec pour chacun le résultat attendu et le résultat obtenu, exécuté sur les deux thèmes et aux trois points de rupture." },
      { t: 'tab', titre: "Jeu d'essai du parcours d'achat (extrait)",
        entetes: ['Cas provoqué', 'Résultat attendu'],
        largeurs: [4680, 4680],
        lignes: [
          ['Quantité supérieure au stock disponible', 'Refus, quantité disponible indiquée'],
          ['Produit en rupture ajouté au panier', 'Refus explicite, article signalé'],
          ['Validation avec un panier vide', 'Refus, code 400'],
          ['Commande lancée sans être connecté', 'Redirection vers la connexion, panier conservé'],
          ["Consultation de la commande d'un autre client", 'Introuvable, code 404'],
          ['Deux commandes simultanées sur le dernier exemplaire', 'Une seule aboutit, stock jamais négatif'],
        ],
        legende: "Six des douze cas du jeu d'essai. Les huit cas d'erreur ont été provoqués volontairement." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Langage : JavaScript ES2020 (fetch, async/await, localStorage, manipulation du DOM).',
        'Outils : Visual Studio Code, outils de développement du navigateur (console et onglet réseau), ESLint, Git.',
        'Environnement : API REST Node.js/Express en local, base MySQL peuplée de plus de 3 000 produits réels importés depuis une source publique.',
        "Documentation : MDN Web Docs et documentation de l'API Fetch en anglais, fiches OWASP sur les failles de type XSS.",
      ] },
    ],
    avecQui: [
      { t: 'p', v: 'Travail réalisé seul.' },
      { t: 'p', v: "J'ai sollicité mon formateur sur la gestion de l'état du panier entre le stockage local et le compte : il m'a orienté vers une fusion à la connexion plutôt que vers une synchronisation permanente, plus simple et plus prévisible." },
    ],
    periode: 'Du 04/05/2026 au 29/05/2026',
    infos: [
      { t: 'p', v: "Le catalogue de démonstration compte plus de 3 000 références, ce qui m'a permis de constater des lenteurs qu'un jeu de dix produits n'aurait jamais révélées. C'est ce volume qui m'a conduit à faire filtrer et paginer par la base." },
      { t: 'p', v: "La perte du panier à la connexion est un défaut que je n'avais pas anticipé. Je l'ai découvert en déroulant le parcours complet de bout en bout, et non en testant les fonctions isolément. Depuis, je teste les parcours autant que les fonctions." },
    ],
  },
];
