// at2.js : Activité-type 2 (back-end) : une compétence par exemple.
const AT2 = "Développer la partie back-end d'une application web ou web mobile sécurisée";

module.exports = [
  // ══════════════════════════════════════════════════════════════ CP 5
  {
    at: 2, atTitre: AT2, ex: 1,
    titre: 'Mettre en place une base de données relationnelle',
    cps: ['CP 5 : Mettre en place une base de données relationnelle'],
    taches: [
      { t: 'h', v: '1) Du modèle conceptuel au schéma physique' },
      { t: 'p', v: "J'ai conçu et mis en place la base de données de la boutique en suivant la méthode Merise. J'ai commencé par un modèle conceptuel, en identifiant les entités principales, Utilisateur, Produit, Commande, Éditeur, Série et Annonce, et les associations qui les relient, avec leurs cardinalités." },
      { t: 'p', v: "Certaines associations portent leurs propres données, ce qui a orienté la traduction : le panier relie un utilisateur et un produit mais porte une quantité ; l'avis relie un utilisateur et un produit mais porte une note et un commentaire. À l'inverse, l'association entre un produit et son éditeur est un simple un-à-plusieurs." },
      { t: 'pic', file: '02_cahier_des_charges/15_mcd.png', w: 620,
        caption: "Modèle conceptuel de données (méthode Merise) : six entités, leurs associations et leurs cardinalités. Les trois associations porteuses, panier, avis et ligne de commande, deviendront des tables à part entière." },
      { t: 'p', v: "J'ai traduit ce modèle en schéma physique : chaque entité devient une table, chaque association plusieurs-à-plusieurs devient une table de liaison, chaque association un-à-plusieurs devient une clé étrangère. La base compte dix-sept tables, douze dans le schéma initial et cinq ajoutées ensuite par migrations. J'ai adopté des règles de nommage homogènes, appliquées sans exception : tables au pluriel, colonnes en minuscules avec séparateur bas, clés étrangères suffixées par « _id », index préfixés par « idx_ » et contraintes d'unicité par « uq_ »." },
      { t: 'pic', file: '02_cahier_des_charges/16_mpd.png', w: 620,
        caption: "Schéma relationnel : les dix-sept tables, leurs clés primaires et leurs clés étrangères. Ce schéma est lu dans database/schema.sql et les migrations, il ne peut donc pas diverger de la base installée." },
      { t: 'h', v: '2) Intégrité, sécurité et confidentialité des données' },
      { t: 'p', v: "J'ai retenu le moteur InnoDB, seul à assurer à la fois le respect des clés étrangères et la gestion des transactions dont j'avais besoin pour le passage de commande." },
      { t: 'p', v: "J'ai déclaré les contraintes d'intégrité : clés primaires sur toutes les tables, unicité sur l'adresse email et sur le nom d'utilisateur, clés primaires composées sur le panier et les favoris pour interdire structurellement les doublons, et suppressions en cascade sur tout ce qui dépend d'un compte, afin qu'une suppression de compte n'abandonne aucune donnée orpheline. Cette dernière règle répond aussi à l'obligation d'effacement prévue par le RGPD. J'ai ajouté des index sur les colonnes les plus filtrées : catégorie, état, indicateurs commerciaux et statut de commande." },
      { t: 'p', v: "Aucune donnée sensible n'est stockée en clair. Les mots de passe sont hachés, et les jetons de vérification d'adresse ou de réinitialisation ne sont conservés que sous forme d'empreinte. Le compte applicatif utilisé par l'API dispose des seuls droits de lecture et d'écriture sur la base du projet, à l'exclusion de tout droit d'administration du serveur ; ses identifiants sont lus dans des variables d'environnement et ne sont jamais versionnés." },
      { t: 'h', v: '3) Migrations versionnées et idempotentes' },
      { t: 'p', v: "J'ai fait évoluer le schéma en cours de projet à l'aide de scripts de migration versionnés et idempotents : chacun vérifie l'état du schéma dans information_schema avant d'agir, ce qui permet de le rejouer sans erreur sur une base déjà à jour. Cette précaution m'a servi à chaque réinstallation du projet et à chaque reprise d'une sauvegarde antérieure." },
      { t: 'code', caption: 'database/migrations/002_verification_email.sql : ajout de colonne rejouable', lines: [
        '-- Idempotente : chaque ajout est gardé par une vérification dans',
        '-- information_schema, la migration peut être rejouée sans erreur.',
        'SET @sql := IF(',
        '  (SELECT COUNT(*) FROM information_schema.COLUMNS',
        '     WHERE TABLE_SCHEMA = DATABASE()',
        "       AND TABLE_NAME  = 'utilisateurs'",
        "       AND COLUMN_NAME = 'email_verifie') = 0,",
        "  'ALTER TABLE `utilisateurs` ADD COLUMN `email_verifie` TINYINT(1)",
        "     NOT NULL DEFAULT 0 AFTER `email`',",
        "  'DO 0');",
        'PREPARE st FROM @sql; EXECUTE st; DEALLOCATE PREPARE st;',
      ] },
      { t: 'h', v: "4) Jeu d'essai et sauvegarde" },
      { t: 'p', v: "J'ai constitué un jeu d'essai réaliste plutôt qu'un jeu minimal : plus de 3 000 produits importés depuis une source publique et enrichis de leurs couvertures, des comptes de test couvrant chaque rôle (visiteur, client vérifié, client non vérifié, administrateur) et des commandes à différents statuts. Ce volume a révélé des lenteurs qu'une dizaine de lignes n'aurait jamais montrées, et c'est lui qui a motivé les index et la pagination côté base." },
      { t: 'p', v: "La base est sauvegardée avec mysqldump sous forme d'un fichier SQL complet, structure et données, restaurable en une seule commande. J'ai vérifié cette restauration en la rejouant sur une base vide." },
    ],
    moyens: [
      { t: 'ul', v: [
        'SGBD : MySQL 8, moteur de stockage InnoDB.',
        "Outils : phpMyAdmin et client MySQL en ligne de commande, Visual Studio Code pour l'écriture des scripts SQL, mysqldump pour les sauvegardes, Git pour le versionnement des migrations.",
        'Méthode : Merise, modèle conceptuel puis modèle physique de données.',
        'Documentation : documentation officielle MySQL en anglais, supports de formation sur la modélisation relationnelle.',
      ] },
    ],
    avecQui: [
      { t: 'p', v: 'Travail réalisé seul.' },
      { t: 'p', v: "J'ai soumis mon modèle conceptuel à mon formateur avant de passer au modèle physique. Sa remarque sur la conservation du prix dans les lignes de commande a modifié ma conception : je me contentais initialement de pointer vers le produit." },
    ],
    periode: 'Du 30/03/2026 au 17/04/2026',
    infos: [
      { t: 'p', v: "Le fait de dupliquer le titre et le prix dans les lignes de commande est une dénormalisation volontaire. Si le prix change six mois plus tard, ou si l'article sort du catalogue, la commande passée doit rester fidèle à ce que le client a réellement payé. C'est le point de conception qui m'a le plus fait réfléchir, parce qu'il va à l'encontre de la règle de normalisation apprise en cours." },
    ],
  },

  // ══════════════════════════════════════════════════════════════ CP 6
  {
    at: 2, atTitre: AT2, ex: 2,
    titre: "Développer des composants d'accès aux données SQL et NoSQL",
    cps: ["CP 6 : Développer des composants d'accès aux données SQL et NoSQL"],
    taches: [
      { t: 'h', v: "1) Organisation de la couche d'accès aux données" },
      { t: 'p', v: "J'ai développé la couche d'accès aux données du serveur dans une architecture MVC : middlewares, routes, contrôleurs et modèles, chacun dans son répertoire. Les modèles sont les seuls fichiers du projet à contenir du SQL ; un contrôleur qui écrirait une requête serait immédiatement repérable en relecture." },
      { t: 'p', v: "J'ai centralisé la connexion dans un pool de dix connexions réutilisables plutôt que d'ouvrir une connexion par requête, et j'ai fait échouer le démarrage du serveur si la base est injoignable, plutôt que de laisser l'application accepter des requêtes qu'elle ne pourra pas servir." },
      { t: 'code', caption: 'server/src/config/db.js : pool de connexions', lines: [
        "const mysql = require('mysql2/promise');",
        '',
        'const pool = mysql.createPool({',
        "  host: process.env.DB_HOST || 'localhost',",
        "  database: process.env.DB_NAME || 'kinka_db',",
        '  user: process.env.DB_USER,',
        '  password: process.env.DB_PASS,',
        "  waitForConnections: true,   // met en file d'attente si le pool est saturé",
        '  connectionLimit: 10,        // 10 connexions simultanées au maximum',
        "  charset: 'utf8mb4'",
        '});',
      ] },
      { t: 'h', v: '2) Requêtes préparées et liste blanche' },
      { t: 'p', v: "J'ai écrit tous les accès aux données, en consultation, création, modification et suppression, en utilisant systématiquement des requêtes préparées : les valeurs sont transmises séparément du texte SQL et ne peuvent donc jamais être interprétées comme du code." },
      { t: 'p', v: "Pour les requêtes filtrées du catalogue, j'ai construit la clause WHERE en assemblant des fragments écrits dans le code et en accumulant les valeurs dans un tableau de paramètres. Pour le tri, où un paramètre préparé est techniquement impossible puisqu'il s'agit d'un fragment de requête et non d'une valeur, j'ai utilisé une liste blanche : la clé publique reçue est traduite en clause SQL, et une valeur inconnue retombe silencieusement sur le tri par défaut. J'ai également borné la pagination, pour qu'une requête ne puisse pas réclamer la totalité de la table." },
      { t: 'code', caption: 'server/src/models/produitModel.js : liste blanche des tris et bornage', lines: [
        '// Tris autorisés : la clé publique est traduite en clause SQL, ce qui',
        "// interdit d'injecter une expression arbitraire dans l'ORDER BY.",
        'const TRIS = {',
        "  titre:     'titre ASC',",
        "  prix_asc:  'prix ASC',",
        "  prix_desc: 'prix DESC',",
        "  note:      'note DESC',",
        "  nouveaute: 'created_at DESC'",
        '};',
        '',
        'async function lister(filtres = {}) {',
        '  const { where, params } = construireFiltres(filtres);',
        '  const order  = TRIS[filtres.sort] || TRIS.titre;',
        '  const limit  = Math.min(Math.max(Number(filtres.limit) || 50, 1), 500);',
        '  const offset = Math.max(Number(filtres.offset) || 0, 0);',
        '  const [rows] = await db.query(',
        '    `SELECT * FROM produits WHERE ${where} ORDER BY ${order}',
        '       LIMIT ? OFFSET ?`, [...params, limit, offset]);',
        '  ...',
        '}',
      ] },
      { t: 'h', v: "3) Conflits d'accès : le stock négatif" },
      { t: 'p', v: "Le point le plus délicat du projet a été le passage de commande. Deux clients qui valident au même instant alors qu'il reste un seul exemplaire peuvent tous deux passer le contrôle de stock avant qu'aucun ne l'ait décrémenté : le stock devient négatif et une commande ne peut plus être honorée. Ce défaut est invisible en test manuel, puisqu'on est toujours seul quand on clique soi-même." },
      { t: 'p', v: "J'ai donc enfermé toute l'opération dans une transaction unique et verrouillé les lignes produit avec SELECT … FOR UPDATE jusqu'à la validation. J'ai ajouté une clause ORDER BY pour fixer l'ordre de verrouillage et éviter les interblocages lorsque deux commandes portent sur les mêmes articles dans un ordre différent. J'ai complété par un décrément conditionnel du stock en guise de garde-fou. En cas d'échec à n'importe quelle étape, un ROLLBACK annule l'ensemble : la base ne conserve jamais une commande à moitié créée." },
      { t: 'code', caption: 'server/src/models/commandeModel.js : création de commande transactionnelle', lines: [
        'async function creerDepuisPanier(userId, adresseLivraison) {',
        '  const conn = await db.getConnection();   // connexion dédiée',
        '  try {',
        '    await conn.beginTransaction();',
        '',
        "    // Les lignes produits sont verrouillées (FOR UPDATE) jusqu'au commit :",
        '    // sans ce verrou, deux acheteurs simultanés passaient tous deux la',
        "    // vérification de stock avant qu'aucun ne l'ait décrémenté.",
        "    // ORDER BY fixe l'ordre de verrouillage (anti-interblocage).",
        '    const [items] = await conn.query(',
        '      `SELECT p.id, p.titre, p.stock, pa.quantite',
        '         FROM panier pa JOIN produits p ON p.id = pa.produit_id',
        '        WHERE pa.user_id = ? ORDER BY p.id FOR UPDATE`, [userId]);',
        '',
        '    if (!items.length) { await conn.rollback();',
        "      return { ok: false, statut: 400, erreur: 'Le panier est vide' }; }",
        '',
        '    const rupture = items.find(i => i.stock < i.quantite);',
        '    if (rupture) { await conn.rollback();',
        '      return { ok: false, statut: 400,',
        '               erreur: `Stock insuffisant pour "${rupture.titre}"` }; }',
        '',
        '    for (const item of items) {',
        '      // Décrément conditionnel : garde-fou si le stock a bougé.',
        '      const [dec] = await conn.query(',
        "        'UPDATE produits SET stock = stock - ? WHERE id = ? AND stock >= ?',",
        '        [item.quantite, item.id, item.quantite]);',
        '      if (dec.affectedRows === 0) { await conn.rollback();',
        "        return { ok: false, statut: 409, erreur: 'Stock insuffisant' }; }",
        '    }',
        '',
        "    await conn.query('DELETE FROM panier WHERE user_id = ?', [userId]);",
        '    await conn.commit();',
        '    return { ok: true, commande: { id, total, articles: items } };',
        '  } catch (err) { await conn.rollback(); throw err; }',
        '  finally { conn.release(); }',
        '}',
      ] },
      { t: 'pic', file: '02_cahier_des_charges/17_sequence_commande.png', w: 620,
        caption: "Diagramme de séquence du test d'accès concurrent : le verrou pris par la transaction A fait attendre la B, qui lit ensuite un stock à zéro et reçoit un refus. C'est ce comportement que le jeu d'essai vérifie." },
      { t: 'p', v: "Le numéro de commande lisible, de la forme CMD-2026-0042, est produit par un compteur incrémenté de façon atomique dans la même transaction : la ligne du compteur est verrouillée le temps de l'incrément, si bien que deux commandes simultanées ne peuvent pas obtenir le même numéro. Un rollback laisse au pire un trou dans la numérotation, jamais un doublon." },
      { t: 'h', v: "4) Cas d'exception, validation des entrées et performance" },
      { t: 'p', v: "Chaque accès aux données traite explicitement ses cas d'exception et renvoie un code HTTP adapté plutôt qu'une erreur générique : 400 pour un panier vide ou un stock insuffisant constaté à la lecture, 409 pour un conflit détecté à l'écriture, 404 pour une ressource absente, 403 pour une ressource qui n'appartient pas à l'appelant. Une commande n'est lisible que par son propriétaire, la condition portant sur l'identifiant du client dans la requête SQL elle-même et non sur un contrôle applicatif que l'on pourrait oublier." },
      { t: 'p', v: "Les entrées sont validées avant tout accès à la base par un middleware dédié, qui contrôle la présence, le type et le format de chaque champ attendu ; les entiers issus de l'URL sont convertis et bornés." },
      { t: 'p', v: "J'ai enfin corrigé un problème de requêtes en cascade : l'affichage de l'historique déclenchait une requête par commande pour en charger les articles. J'ai remplacé cette boucle par une requête unique utilisant IN, puis un regroupement en mémoire. Dix commandes passent ainsi de onze requêtes à deux." },
      { t: 'h', v: '5) Tests' },
      { t: 'p', v: "J'ai vérifié le comportement concurrent en lançant deux requêtes de commande simultanées sur un produit dont j'avais forcé le stock à un exemplaire : une seule aboutit, l'autre reçoit un refus explicite, le stock finit à zéro et jamais en négatif. J'ai également testé les injections SQL classiques dans les champs de recherche et dans les paramètres de tri, et vérifié qu'une valeur inconnue retombait bien sur le tri par défaut." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Langage et bibliothèques : Node.js, Express 4, pilote mysql2 avec interface à promesses.',
        "Notions mobilisées : transactions et propriétés ACID, verrous d'écriture, niveaux d'isolation, requêtes préparées, architecture MVC.",
        "Outils : Visual Studio Code, client HTTP pour appeler l'API, console MySQL pour observer les verrous en cours, ESLint, Git.",
        "Documentation : documentation MySQL sur le verrouillage et les niveaux d'isolation, documentation mysql2 en anglais, fiche OWASP sur l'injection SQL.",
      ] },
    ],
    avecQui: [
      { t: 'p', v: 'Travail réalisé seul.' },
      { t: 'p', v: "J'ai exposé le problème du stock négatif à mon formateur, qui m'a confirmé la piste des transactions et m'a alerté sur le risque d'interblocage, un point auquel je n'avais pas pensé et qui m'a conduit à ajouter la clause ORDER BY." },
    ],
    periode: 'Du 20/04/2026 au 07/05/2026',
    infos: [
      { t: 'p', v: "C'est le sujet qui m'a le plus appris pendant le projet : la théorie des transactions est devenue concrète le jour où j'ai rencontré le problème qu'elle résout. J'ai aussi retenu qu'un défaut de concurrence ne se trouve pas en cliquant, mais en reproduisant délibérément la simultanéité." },
    ],
  },

  // ══════════════════════════════════════════════════════════════ CP 7
  {
    at: 2, atTitre: AT2, ex: 3,
    titre: 'Développer des composants métier coté serveur',
    cps: ['CP 7 : Développer des composants métier coté serveur'],
    taches: [
      { t: 'h', v: '1) Style défensif et traitement des erreurs' },
      { t: 'p', v: "J'ai développé les traitements côté serveur dans un style défensif. Chaque contrôleur est enveloppé dans un gestionnaire d'asynchrone qui relaie toute erreur au traitement global, de sorte qu'aucune exception ne peut laisser une requête sans réponse ni faire tomber le serveur. Le détail technique des erreurs est journalisé côté serveur mais n'est jamais renvoyé au client." },
      { t: 'h', v: '2) Composants métier de gestion des comptes' },
      { t: 'p', v: "J'ai haché les mots de passe avec bcrypt au coût 12 : ils ne sont jamais stockés en clair et je suis moi-même incapable de les retrouver. J'ai mis en place l'authentification par jeton JWT signé, transmis dans l'en-tête de chaque requête protégée et vérifié par un middleware." },
      { t: 'p', v: "J'ai ajouté la confirmation de l'adresse email par un lien à usage unique, ainsi que la réinitialisation du mot de passe. Dans les deux cas, le jeton envoyé n'est jamais stocké en base : seule son empreinte SHA-256 l'est, exactement comme un mot de passe. Une fuite de la base ne permettrait donc pas de prendre la main sur un compte." },
      { t: 'p', v: "J'ai veillé à ne rien divulguer. La réponse est strictement identique que l'adresse soit inconnue ou le mot de passe erroné, faute de quoi le formulaire de connexion deviendrait un moyen de découvrir quels comptes existent. Le même principe s'applique à la fonction « mot de passe oublié », qui répond toujours de la même manière." },
      { t: 'p', v: "J'ai limité les tentatives à dix par quart d'heure sur l'authentification et à cent requêtes par minute sur l'API, ajouté un champ leurre invisible que seuls les robots remplissent, et refusé les mots de passe connus des attaquants. Ce dernier contrôle repose d'abord sur une liste locale des mots de passe les plus utilisés, sans dépendance ni latence, et en option sur le service Have I Been Pwned interrogé par k-anonymat : seuls les cinq premiers caractères de l'empreinte SHA-1 sont transmis, le service ne peut donc pas savoir quel mot de passe était testé. En cas d'indisponibilité de ce service, l'inscription reste possible, car un tiers en panne ne doit pas bloquer le métier." },
      { t: 'h', v: "3) Back-office et contrôle d'accès" },
      { t: 'p', v: "J'ai développé le back-office d'administration, qui couvre la gestion du catalogue, des commandes, des utilisateurs et des messages de contact. Il est protégé par une double vérification, authentification puis rôle, appliquée en un seul point au montage du routeur, de sorte qu'aucune route d'administration ne puisse être oubliée. Le rôle est relu en base à chaque appel et non lu dans le jeton, afin qu'un retrait de droits prenne effet immédiatement sans attendre l'expiration du jeton." },
      { t: 'code', caption: 'server/src/middleware/admin.js : contrôle du rôle relu en base', lines: [
        "// À utiliser APRÈS authRequired : vérifie que l'utilisateur connecté a le",
        "// rôle 'admin'. Le rôle est relu en base à chaque appel (source de vérité),",
        '// donc un retrait de droits prend effet immédiatement.',
        'async function adminRequired(req, res, next) {',
        '  try {',
        '    if (!req.user || !req.user.id) {',
        "      return res.status(401).json({ success: false, error: 'Connexion requise' });",
        '    }',
        '    const [rows] = await db.query(',
        "      'SELECT role FROM utilisateurs WHERE id = ?', [req.user.id]);",
        "    if (!rows[0] || rows[0].role !== 'admin') {",
        '      return res.status(403).json({ success: false,',
        "        error: 'Accès réservé aux administrateurs' });",
        '    }',
        '    next();',
        '  } catch (err) { next(err); }',
        '}',
      ] },
      { t: 'p', v: "Chaque action sensible est tracée dans un journal d'audit : auteur, action, cible et adresse IP. La journalisation ne peut jamais faire échouer l'action métier ; si l'écriture du journal échoue, l'erreur est consignée côté serveur et l'opération se poursuit." },
      { t: 'pic', file: '04_maquettes/bureau/42_admin_tableau_de_bord.png', w: 580,
        caption: "Back-office, tableau de bord. Les neuf sections (catalogue, commandes, avis, annonces, messages, newsletter, utilisateurs, journal d'audit) sont protégées en un seul point, au montage du routeur." },
      { t: 'h', v: '4) Conformité et qualité du code' },
      { t: 'p', v: "J'ai mis en place les pages légales exigées par le RGPD, à savoir les conditions générales d'utilisation, les conditions générales de vente, la politique de retour et les mentions légales, et rendu le consentement explicite à l'inscription. Le nommage des fichiers, des fonctions et des tables suit une convention unique en français, documentée dans le README, et chaque fichier porte un en-tête expliquant son rôle. La qualité du code est contrôlée par ESLint et Prettier avant chaque livraison." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Bibliothèques : bcryptjs, jsonwebtoken, express-rate-limit, nodemailer, module crypto de Node.js.',
        "Notions mobilisées : hachage et salage, jetons signés, contrôle d'accès par rôle, journalisation, programmation défensive, gestion des secrets par variables d'environnement.",
        'Outils : Visual Studio Code, client HTTP, boîte de réception de test Ethereal pour vérifier le rendu des emails sans serveur SMTP, ESLint, Git.',
        "Documentation : OWASP Top 10, recommandations de l'ANSSI, recommandation NIST SP 800-63B sur les mots de passe en anglais, service Have I Been Pwned.",
      ] },
    ],
    avecQui: [
      { t: 'p', v: 'Travail réalisé seul.' },
      { t: 'p', v: "Mon formateur a relu la partie authentification et m'a fait remarquer que mon message d'erreur de connexion distinguait l'adresse inconnue du mot de passe faux, ce qui permettait d'énumérer les comptes. J'ai corrigé ce point ainsi que la fonction de mot de passe oublié." },
    ],
    periode: 'Du 11/05/2026 au 29/05/2026',
    infos: [
      { t: 'p', v: "J'ai mené une reprise de sécurité en fin de projet : j'ai relu l'ensemble du code en dressant la liste écrite de ce qui n'allait pas, puis traité les points un par un, du plus grave au plus anodin. Cette reprise m'a appris à traiter la sécurité comme une revue méthodique et documentée plutôt que comme une série de réflexes." },
    ],
  },

  // ══════════════════════════════════════════════════════════════ CP 8
  {
    at: 2, atTitre: AT2, ex: 4,
    titre: "Documenter le déploiement d'une application dynamique web ou web mobile",
    cps: ["CP 8 : Documenter le déploiement d'une application dynamique web ou web mobile"],
    taches: [
      { t: 'h', v: '1) La procédure de déploiement' },
      { t: 'p', v: "J'ai rédigé la procédure de déploiement de l'application sous la forme d'un guide numéroté, pensé pour quelqu'un qui découvre le projet. Il énumère les prérequis avec les versions minimales de Node, npm, MySQL et Git et la commande permettant de vérifier chacune, puis l'installation des dépendances, la création et l'import de la base, la configuration des variables d'environnement à partir du fichier d'exemple versionné, le peuplement du catalogue, la création du compte administrateur, le lancement du serveur et du front, le parcours de recette à dérouler pour valider l'installation, et une section de résolution des problèmes fréquents." },
      { t: 'code', caption: 'docs/INSTALL.md : prérequis vérifiables et étapes numérotées (extrait)', lines: [
        "# GUIDE D'INSTALLATION, Kinka",
        '',
        '## 1. Prerequis',
        '',
        '| Outil   | Version min.         | Verifier avec     |',
        '|---------|----------------------|-------------------|',
        '| Node.js | 18 ou +              | `node -v`         |',
        '| npm     | 9 ou +               | `npm -v`          |',
        '| MySQL   | 8 (ou MariaDB 10.5+) | `mysql --version` |',
        "| Git     | n'importe quelle     | `git --version`   |",
        '',
        '## 6. Creer la base de donnees',
        '',
        '    mysql -u root -p -e "CREATE DATABASE kinka_db"',
        '    mysql -u root -p kinka_db < database/schema.sql',
        '    mysql -u root -p kinka_db < database/migrations/001_admin_support.sql',
        '    mysql -u root -p kinka_db < database/migrations/002_verification_email.sql',
        '',
        '## 7. Configurer .env',
        '',
        '    cp .env.example .env      # puis renseigner DB_PASS et JWT_SECRET',
        '',
        '## 12. Tester le parcours complet',
        "    Derouler les 12 cas du jeu d'essai avant de considerer",
        "    l'installation comme valide.",
      ] },
      { t: 'h', v: '2) Les scripts qui accompagnent le déploiement' },
      { t: 'p', v: "J'ai documenté les scripts qui accompagnent ce déploiement : import du catalogue depuis une source publique, récupération des couvertures, promotion d'un compte au rôle administrateur, et migrations SQL. Pour chacun, le guide précise ce qu'il fait, comment le lancer et ce qu'il faut observer en sortie. Les migrations étant idempotentes, la procédure peut être rejouée sur une installation existante sans risque." },
      { t: 'p', v: "J'ai également documenté les dépendances externes et leurs versions, ainsi que les variables d'environnement attendues, dans un fichier .env.example versionné. Une variable manquante fait échouer le démarrage avec un message explicite plutôt que de laisser l'application démarrer dans un état incohérent." },
      { t: 'h', v: '3) Vérification de la procédure' },
      { t: 'p', v: "J'ai vérifié cette documentation en réinstallant l'application de zéro sur une machine vierge, à partir du seul dépôt et du seul guide, afin de m'assurer qu'aucune étape implicite ne manquait. Deux oublis sont apparus à cette occasion : une variable d'environnement non documentée et l'ordre d'exécution des migrations. J'ai ensuite fait dérouler la procédure par un autre stagiaire, dont les blocages m'ont servi à la compléter une seconde fois." },
      { t: 'h', v: '4) Veille et perspective de déploiement continu' },
      { t: 'p', v: "Ma veille sur le déploiement porte sur la démarche DevOps et les chaînes d'intégration continue. J'ai identifié les étapes de ma procédure qui seraient automatisables dans une telle chaîne, à savoir l'installation des dépendances, le contrôle ESLint et l'application des migrations, et celles qui resteraient manuelles, comme la création du compte administrateur et la recette fonctionnelle. C'est la suite logique de ce travail si l'application devait être mise en production." },
    ],
    moyens: [
      { t: 'ul', v: [
        'Format : guide Markdown versionné dans le dépôt (docs/INSTALL.md), lisible directement sur GitHub.',
        'Scripts documentés : import du catalogue, récupération des couvertures, promotion administrateur, migrations SQL idempotentes.',
        "Configuration : fichier .env.example versionné, décrivant chaque variable d'environnement attendue.",
        "Vérification : réinstallation complète sur machine vierge, puis relecture par un autre stagiaire.",
        "Veille : documentation GitHub Actions, articles sur l'intégration et le déploiement continus.",
      ] },
    ],
    avecQui: [
      { t: 'p', v: 'Travail réalisé seul.' },
      { t: 'p', v: "J'ai fait dérouler la procédure d'installation par un autre stagiaire de ma promotion, sans l'aider. Les trois endroits où il a hésité sont ceux que j'ai réécrits : c'est la seule manière que j'aie trouvée de vérifier qu'une documentation est complète, puisque son auteur connaît déjà les étapes implicites." },
    ],
    periode: 'Du 01/06/2026 au 05/06/2026',
    infos: [
      { t: 'p', v: "Écrire la procédure a révélé des choix que je n'avais jamais formalisés, comme l'ordre dans lequel les migrations doivent être appliquées. Documenter le déploiement n'a donc pas seulement produit un guide : cela a aussi corrigé le projet lui-même." },
      { t: 'p', v: "J'ai découvert à cette occasion qu'un secret s'était retrouvé dans l'historique Git. Je l'ai purgé en réécrivant l'historique, j'ai renouvelé la valeur compromise et renforcé le fichier .gitignore. Un secret exposé une fois doit être remplacé, même s'il a été retiré du code." },
    ],
  },
];
