// cdc_contenu.js : contenu du cahier des charges Kinka.fr.
// Blocs : h1, h2, p, ul, tab, pic, encadre, saut.

const F = '02_cahier_des_charges';
const DS = '01_design_system';

module.exports = [
  // ═══════════════════════════════════════════════════ 1
  { t: 'h1', v: '1. Présentation du projet' },

  { t: 'h2', v: '1.1 Contexte' },
  { t: 'p', v: "La France est le deuxième marché du manga au monde après le Japon. L'offre en ligne y est pourtant dominée par des enseignes généralistes, où le manga n'est qu'un rayon parmi d'autres, et par des plateformes d'occasion qui ne connaissent pas les particularités du support." },
  { t: 'p', v: "Kinka.fr est une boutique en ligne spécialisée dans la vente de mangas neufs et d'occasion. Le projet vise un public de lecteurs réguliers, qui suivent des séries longues, achètent plusieurs tomes par mois et revendent ceux qu'ils ont lus." },

  { t: 'h2', v: '1.2 Le problème à résoudre' },
  { t: 'p', v: "Trois constats sont à l'origine du projet. Ils ont gouverné l'ensemble des décisions de conception qui suivent." },
  { t: 'tab',
    entetes: ['Constat', 'Conséquence sur la conception'],
    largeurs: [3800, 5560], premiereGras: true,
    lignes: [
      ["Un lecteur qui suit une série cherche « le tome 47 », pas « un manga ». Certaines séries dépassent cent volumes.",
       "La navigation doit partir de la série, et pas seulement du catalogue global. Une fiche série listant les tomes dans l'ordre de parution devient indispensable."],
      ["Sur l'occasion, l'acheteur ne peut pas manipuler le livre avant d'acheter.",
       "L'état doit être décrit selon une échelle explicite, accompagné de photos réelles et de l'identité du vendeur. Le stock doit être affiché en nombre d'exemplaires."],
      ["Un catalogue de plus de 3 000 références est inutilisable sans outils de tri.",
       "Filtres croisés, recherche avec suggestions au fil de la frappe, et pagination exécutée par la base de données."],
    ] },

  { t: 'h2', v: '1.3 Objectifs et indicateurs' },
  { t: 'p', v: "Six objectifs sont retenus. Chacun est associé à une mesure : un objectif sans mesure ne peut pas être déclaré atteint. Ces mesures servent de critères de recette en fin de projet." },
  { t: 'tab',
    entetes: ['Objectif', "Ce qu'il impose", 'Indicateur'],
    largeurs: [2100, 4560, 2700], premiereGras: true,
    lignes: [
      ['Trouver vite', "Atteindre une fiche produit en trois clics au maximum depuis l'accueil", 'Profondeur de navigation inférieure ou égale à 3'],
      ['Ne pas perdre le panier', 'Un panier constitué hors connexion doit survivre à la connexion', 'Taux de perte de panier : 0 %'],
      ['Ne jamais survendre', 'Aucune commande ne doit dépasser le stock disponible', 'Stock négatif : 0 occurrence'],
      ['Rester utilisable sur mobile', 'Tous les parcours doivent aboutir à 390 pixels de large', '100 % des parcours testés'],
      ['Rester accessible', 'Contrastes conformes au niveau AA sur les deux thèmes', 'Rapport supérieur ou égal à 4,5:1 sur le texte'],
      ['Rester autonome', 'La boutique se gère sans intervention sur le code', '0 modification de code pour une tâche courante'],
    ] },
  { t: 'pic', file: `${F}/01_contexte_objectifs.png`, w: 600,
    caption: 'Figure 1. Contexte, problème à résoudre, objectifs mesurables et périmètre.' },

  { t: 'h2', v: '1.4 Ce que le site n\'est pas' },
  { t: 'ul', v: [
    "Ce n'est pas un magazine : pas de longs contenus éditoriaux en page d'accueil.",
    "Ce n'est pas un réseau social : les avis et les annonces existent, mais ne structurent pas la navigation.",
    "Ce n'est pas une marketplace généraliste : le catalogue reste le cœur du site, les annonces entre membres sont une section secondaire.",
  ] },

  { t: 'h2', v: '1.5 Hors périmètre' },
  { t: 'p', v: "Une limite écrite est une décision ; une limite tue est un oubli. Les points suivants sont explicitement exclus, avec leur justification." },
  { t: 'tab',
    entetes: ['Exclusion', 'Motif'],
    largeurs: [3200, 6160], premiereGras: true,
    lignes: [
      ['Paiement bancaire réel', "La conformité PCI-DSS dépasse le cadre du projet. L'étape existe et crée la commande, mais aucune donnée bancaire ne circule."],
      ['Rendu côté serveur', "Les fiches étant injectées en JavaScript, un moteur qui n'exécute pas les scripts verra une page vide. Un référencement marchand réel imposerait un rendu serveur."],
      ['Retours et remboursements', "La règle est publiée et la demande enregistrée ; le traitement reste manuel."],
      ['Facturation comptable', "Le récapitulatif de commande n'est pas une facture au sens comptable."],
      ['Prélèvement de l\'abonnement', "L'interface d'abonnement existe, le prélèvement récurrent non."],
      ['Conteneurisation', "L'environnement de développement repose sur une pile locale ; aucun environnement partagé ne justifiait des conteneurs."],
    ] },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 2
  { t: 'h1', v: '2. Les utilisateurs' },

  { t: 'h2', v: '2.1 Les trois profils' },
  { t: 'p', v: "Chaque écran est pensé pour un profil précis. Un écran qui sert deux profils sert mal les deux." },
  { t: 'tab',
    entetes: ['Profil', 'Ce qu\'il fait', 'Objectif de conception'],
    largeurs: [1800, 4360, 3200], premiereGras: true,
    lignes: [
      ['Visiteur', "Parcourir et filtrer le catalogue, chercher un titre précis, consulter une fiche et les avis, constituer un panier local", "Ne jamais exiger de compte avant la validation de la commande"],
      ['Client connecté', "Panier conservé sur son compte, favoris et avis, commande et suivi de livraison, revente d'occasion entre membres", "Retrouver en deux clics ce qu'il a laissé la dernière fois"],
      ['Administrateur', "Catalogue (ajouter, corriger, retirer), commandes (statut et suivi), modération des avis et annonces, rôles et journal d'audit", "Gérer le quotidien sans jamais toucher au code"],
    ] },

  { t: 'h2', v: '2.2 Les personas' },
  { t: 'p', v: "Quatre profils types, construits à partir des usages réels que le site doit servir. Chacun a tranché au moins une décision de conception, indiquée en dernière colonne." },
  { t: 'tab',
    entetes: ['Persona', 'Situation', 'Ce qui le bloque', 'Ce qu\'il impose'],
    largeurs: [1700, 3000, 2660, 2000], premiereGras: true,
    lignes: [
      ['Léa, 24 ans\nÉtudiante, Lyon\nLa collectionneuse',
       "Suit six séries en cours. Achète chaque nouveau tome dès sa sortie, souvent en occasion. 80 % de ses visites sur mobile.",
       "Les catalogues où il faut chercher « tome 47 » dans une liste non triée. Ne pas savoir dans quel état est le livre d'occasion.",
       "La fiche série et l'affichage du stock réel"],
      ['Thomas, 34 ans\nCadre, Paris\nLe néophyte',
       "Veut offrir un manga à son neveu. N'y connaît rien, ne sait pas par où commencer.",
       "Le jargon employé sans explication. Les listes de 3 000 titres sans hiérarchie.",
       "Les sélections éditoriales de l'accueil"],
      ['Karim, 29 ans\nDéveloppeur, Nantes\nLe revendeur',
       "A accumulé plusieurs centaines de tomes. Veut faire de la place et récupérer un peu d'argent.",
       "Les formulaires interminables pour publier. Ne pas pouvoir modifier une annonce après publication.",
       "Un formulaire d'annonce court, sous deux minutes"],
      ['Camille, 41 ans\nGérante de la boutique\nL\'administratrice',
       "Tient la boutique au quotidien. N'est pas développeuse et ne veut pas dépendre de quelqu'un pour une tâche courante.",
       "Devoir passer par la base de données pour une correction simple. Ne pas savoir qui a modifié quoi.",
       "Le back-office et le journal d'audit"],
    ] },
  { t: 'pic', file: `${F}/02_personas.png`, w: 600,
    caption: 'Figure 2. Les quatre personas, ce qu\'ils cherchent, ce qui les bloque et ce que chacun a tranché.' },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 3
  { t: 'h1', v: '3. Besoins fonctionnels' },

  { t: 'h2', v: '3.1 User stories' },
  { t: 'p', v: "Vingt-quatre besoins, exprimés du point de vue de l'utilisateur et hiérarchisés par la méthode MoSCoW : Must, sans quoi le site ne fonctionne pas ; Should, attendu mais le site tient sans ; Could, améliore l'expérience ; Won't, hors périmètre de cette version." },

  { t: 'h3', v: 'Épopée 1. Parcourir le catalogue' },
  { t: 'tab',
    entetes: ['Prio.', 'En tant que', 'Je veux', 'Afin de'],
    largeurs: [800, 1500, 3800, 3260],
    lignes: [
      ['Must', 'visiteur', 'parcourir le catalogue par catégorie, éditeur et série', "trouver un tome sans connaître son titre exact"],
      ['Must', 'visiteur', 'filtrer par état, prix et disponibilité', "ne voir que ce que je peux réellement acheter"],
      ['Must', 'visiteur', 'rechercher un titre avec des suggestions au fil de la frappe', "aller droit au but quand je sais ce que je cherche"],
      ['Should', 'visiteur', "voir le stock réel en nombre d'exemplaires", "savoir s'il faut me décider vite"],
      ['Could', 'visiteur', "consulter la fiche d'une série et l'ordre de ses tomes", "reprendre une série là où je m'étais arrêté"],
    ] },

  { t: 'h3', v: 'Épopée 2. Acheter' },
  { t: 'tab',
    entetes: ['Prio.', 'En tant que', 'Je veux', 'Afin de'],
    largeurs: [800, 1500, 3800, 3260],
    lignes: [
      ['Must', 'visiteur', 'ajouter au panier sans créer de compte', "ne pas être bloqué avant d'avoir décidé"],
      ['Must', 'client', 'retrouver mon panier après connexion', 'ne pas ressaisir ma sélection'],
      ['Must', 'client', 'être empêché de commander plus que le stock', "ne pas payer un article qui n'arrivera jamais"],
      ['Must', 'client', 'recevoir un numéro de commande lisible', 'pouvoir en parler au service client'],
      ['Should', 'client', "suivre l'avancement et le numéro de colis", 'savoir quand mon colis arrive'],
      ["Won't", 'client', 'payer réellement par carte bancaire', 'la conformité PCI-DSS dépasse le cadre du projet'],
    ] },

  { t: 'h3', v: 'Épopée 3. Gérer mon compte' },
  { t: 'tab',
    entetes: ['Prio.', 'En tant que', 'Je veux', 'Afin de'],
    largeurs: [800, 1500, 3800, 3260],
    lignes: [
      ['Must', 'visiteur', 'créer un compte avec un mot de passe robuste', 'protéger mes données personnelles'],
      ['Must', 'client', 'confirmer mon adresse par un lien reçu par email', "prouver que l'adresse est bien la mienne"],
      ['Must', 'client', "réinitialiser mon mot de passe si je l'oublie", "ne pas perdre l'accès à mon compte"],
      ['Should', 'client', 'enregistrer mon adresse de livraison', 'ne pas la ressaisir à chaque commande'],
      ['Should', 'client', 'supprimer mon compte et toutes mes données', "exercer mon droit à l'effacement"],
    ] },

  { t: 'h3', v: 'Épopée 4. Revendre et participer' },
  { t: 'tab',
    entetes: ['Prio.', 'En tant que', 'Je veux', 'Afin de'],
    largeurs: [800, 1500, 3800, 3260],
    lignes: [
      ['Should', 'membre', "déposer une annonce d'occasion en quelques champs", 'revendre mes tomes sans quitter le site'],
      ['Should', 'membre', 'modifier ou retirer uniquement mes propres annonces', 'garder la maîtrise de ce que je publie'],
      ['Could', 'membre', 'noter et commenter un produit', 'aider les autres lecteurs à choisir'],
      ['Could', 'membre', 'enregistrer des favoris', 'préparer mes prochains achats'],
    ] },

  { t: 'h3', v: 'Épopée 5. Administrer' },
  { t: 'tab',
    entetes: ['Prio.', 'En tant que', 'Je veux', 'Afin de'],
    largeurs: [800, 1500, 3800, 3260],
    lignes: [
      ['Must', 'administratrice', 'modifier prix et stock depuis une interface', 'gérer la boutique sans toucher au code'],
      ['Must', 'administratrice', "changer le statut d'une commande et saisir le suivi", "informer le client de l'avancement"],
      ['Should', 'administratrice', 'modérer les avis et les annonces', 'garder un contenu conforme'],
      ['Should', 'administratrice', 'consulter un journal des actions', 'savoir qui a modifié quoi'],
      ['Could', 'administratrice', 'exporter les inscrits à la newsletter', 'préparer une campagne'],
    ] },
  { t: 'pic', file: `${F}/03_user_stories.png`, w: 560,
    caption: 'Figure 3. Les 24 user stories hiérarchisées par la méthode MoSCoW.' },
  { t: 'saut' },

  { t: 'h2', v: '3.2 Règles de gestion' },
  { t: 'p', v: "Les règles métier que le code doit appliquer, énoncées avant d'être écrites. Une règle non consignée ici est une règle qui dérivera." },
  { t: 'tab',
    entetes: ['Domaine', 'Règles'],
    largeurs: [2000, 7360], premiereGras: true,
    lignes: [
      ['Stock', "Le stock affiché est le stock réel, en nombre d'exemplaires.\nUne commande ne peut jamais faire passer un stock en négatif.\nLe stock est décrémenté à la validation, pas à la mise au panier : un panier ne réserve rien.\nDeux commandes simultanées sur le dernier exemplaire : une seule aboutit, l'autre reçoit un refus explicite avec la quantité disponible.\nQuantité plafonnée à 3 exemplaires du même titre par commande."],
      ['Prix et remises', "Le prix affiché est toujours le prix final, taxes comprises.\nUn prix barré n'apparaît jamais seul : le prix promotionnel est à côté.\nLe prix et le titre sont recopiés dans la ligne de commande : une commande passée reste fidèle à ce que le client a payé, même si le catalogue change.\nLa remise Premium de 10 % s'applique au sous-total, avant les frais de port."],
      ['Panier', "Visiteur : panier conservé dans le navigateur.\nMembre : panier conservé en base, retrouvé sur tout appareil.\nÀ la connexion, le panier local est fusionné dans le compte puis vidé.\nUn article devenu indisponible reste visible dans le panier, signalé, et bloque la validation tant qu'il n'est pas retiré."],
      ['Commande', "Numéro lisible de la forme CMD-2026-0042, unique et sans doublon possible.\nSix statuts, et six seulement : en cours, validée, préparée, expédiée, livrée, annulée.\nLivraison offerte à partir de 50 euros ; 4,90 euros en deçà.\nUne commande est immuable une fois validée : seuls le statut et le numéro de suivi évoluent.\nTout échec en cours de création annule l'ensemble : jamais de commande à moitié créée."],
      ['Compte', "Adresse email unique, confirmée par un lien à usage unique.\nMot de passe : 12 caractères minimum, refusé s'il figure dans les fuites connues.\nDix tentatives de connexion par quart d'heure et par adresse IP.\nLa suppression du compte efface réellement panier, favoris, avis et annonces."],
      ['Annonces entre membres', "Réservées aux membres connectés et vérifiés.\nTrois photos maximum, état obligatoire parmi quatre valeurs.\nUn membre ne modifie et ne retire que ses propres annonces.\nUne annonce signalée reste visible jusqu'à décision de modération, qui est journalisée."],
    ] },
  { t: 'pic', file: `${F}/13_regles_gestion.png`, w: 600,
    caption: 'Figure 4. Les règles de gestion par domaine.' },
  { t: 'saut' },

  { t: 'h2', v: '3.3 Rôles et droits' },
  { t: 'p', v: "Qui a le droit de faire quoi. Chaque ligne est vérifiée côté serveur : masquer un bouton dans l'interface n'est pas un contrôle d'accès." },
  { t: 'tab',
    entetes: ['Action', 'Visiteur', 'Membre', 'Admin.'],
    largeurs: [5760, 1200, 1200, 1200], premiereGras: true,
    lignes: [
      ['Parcourir le catalogue, rechercher, filtrer', 'oui', 'oui', 'oui'],
      ['Consulter une fiche, une série, un auteur', 'oui', 'oui', 'oui'],
      ['Constituer un panier', 'oui', 'oui', 'oui'],
      ['Valider une commande', 'non', 'oui', 'oui'],
      ['Consulter ses propres commandes', 'non', 'oui', 'oui'],
      ["Consulter les commandes d'un tiers", 'non', 'non', 'oui'],
      ['Enregistrer des favoris', 'non', 'oui', 'oui'],
      ['Déposer un avis', 'non', 'oui', 'oui'],
      ['Publier une annonce', 'non', 'oui', 'oui'],
      ['Modifier ou retirer sa propre annonce', 'non', 'oui', 'oui'],
      ["Modifier ou retirer l'annonce d'un tiers", 'non', 'non', 'oui'],
      ['Supprimer son compte et ses données', 'non', 'oui', 'oui'],
      ['Modifier prix, stock et fiches produit', 'non', 'non', 'oui'],
      ["Changer le statut d'une commande", 'non', 'non', 'oui'],
      ['Modérer avis et annonces', 'non', 'non', 'oui'],
      ["Consulter le journal d'audit", 'non', 'non', 'oui'],
      ['Attribuer ou retirer le rôle administrateur', 'non', 'non', 'oui'],
    ] },
  { t: 'encadre', titre: 'Comment le droit est vérifié', lignes: [
    "L'appartenance passe par la requête elle-même : une commande est lue avec « WHERE id = ? AND user_id = ? », et non relue puis comparée en mémoire.",
    "Le rôle est relu en base à chaque appel, jamais lu dans le jeton : un retrait de droits prend effet immédiatement.",
    "La zone d'administration est protégée en un seul point, au montage du routeur : aucune route ne peut être oubliée.",
    "Codes de refus : 401 si aucun jeton ou jeton expiré, 403 si droit insuffisant, 404 pour la ressource d'un tiers, afin de ne pas confirmer son existence.",
  ] },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 4
  { t: 'h1', v: '4. Arborescence et parcours' },

  { t: 'h2', v: '4.1 Arborescence du site' },
  { t: 'p', v: "Le site compte 43 pages, réparties en cinq zones. C'est la zone qui conditionne l'accès." },
  { t: 'tab',
    entetes: ['Zone', 'Contenu', 'Accès'],
    largeurs: [2200, 4960, 2200], premiereGras: true,
    lignes: [
      ['Public', "Accueil, catalogue, fiche produit, recherche, nouveautés, promotions, occasion, meilleures ventes, coups de cœur, coffrets, quatre pages de catégorie, fiche série, fiche auteur, maisons d'édition, fiche éditeur, annonces, dépôt d'annonce, abonnement Premium", 'Sans compte'],
      ['Achat', 'Panier, paiement, confirmation de commande, suivi de commande', 'Compte requis à la validation'],
      ['Compte', "Connexion, inscription, vérification de l'adresse, mot de passe oublié, nouveau mot de passe, confirmation, espace membre, favoris", 'Membre connecté'],
      ['Service et légal', 'Contact, foire aux questions, CGU, CGV, politique de retour, page introuvable', 'Sans compte'],
      ['Back-office', "Tableau de bord, catalogue, commandes, modération des avis, modération des annonces, messages de contact, newsletter, utilisateurs, journal d'audit", 'Rôle administrateur'],
    ] },
  { t: 'pic', file: `${F}/10_arborescence.png`, w: 620,
    caption: "Figure 5. Les 43 pages du site réparties en cinq zones d'accès." },

  { t: 'h2', v: '4.2 Inventaire des écrans à concevoir' },
  { t: 'p', v: "Le nombre de pages HTML ne suffit pas à décrire le travail de conception. Trois pages ne sont que des redirections sans interface, la page d'administration porte neuf sections derrière des onglets, et deux pages ont un second état à dessiner." },
  { t: 'tab',
    entetes: ['Décompte', 'Nombre'],
    largeurs: [7000, 2360], premiereGras: true,
    lignes: [
      ['Pages HTML du site', '43'],
      ['dont redirections sans interface (page_categorie, page_produit, page_oda)', 'moins 3'],
      ['page_admin.html éclatée en ses neuf sections', 'moins 1, plus 9'],
      ['états supplémentaires (favoris vide, compte sans accès)', 'plus 2'],
      ['Écrans à concevoir', '50'],
      ['Cadres à produire : chaque écran en wireframe et en maquette, bureau et mobile', '200'],
    ] },

  { t: 'h2', v: '4.3 Enchaînement des écrans' },
  { t: 'p', v: "Le parcours d'achat nominal compte sept écrans : accueil, catalogue, fiche produit, panier, paiement, confirmation, suivi. Chaque étape doit pouvoir être quittée et reprise sans perte." },
  { t: 'p', v: "Les bifurcations sont les écrans atteints depuis une condition et non depuis un lien de navigation. Ce sont elles qui font les défauts d'un site, et elles doivent être écrites avant d'être codées." },
  { t: 'tab',
    entetes: ['Trajet', 'Condition', 'Effet attendu'],
    largeurs: [2400, 3000, 3960], premiereGras: true,
    lignes: [
      ['Panier vers Connexion', "Le visiteur valide sans être connecté", "Le panier local est poussé vers le compte, puis le paiement reprend où il en était."],
      ['Catalogue vers Recherche', 'Une saisie dans le champ de recherche', "Les suggestions apparaissent dès deux caractères ; la touche entrée ouvre la page de résultats."],
      ['Fiche produit vers Panier', "Clic sur « Ajouter au panier »", "La page n'est jamais quittée : une notification confirme, le badge s'incrémente."],
      ['Paiement vers Panier', 'Stock devenu insuffisant entre-temps', 'Retour au panier avec la quantité disponible indiquée article par article.'],
      ['Inscription vers Vérification', 'Compte créé', "Un lien à usage unique est envoyé ; le compte reste utilisable en lecture."],
      ["Toute page vers Connexion", "Jeton expiré, réponse 401 de l'API", 'La session locale est purgée en un seul point du code, puis retour à la connexion.'],
      ['Toute page vers Page introuvable', 'Identifiant inexistant ou lien obsolète', 'La page propose au moins deux chemins de sortie et des suggestions.'],
      ['Compte vers Accès refusé', 'Page membre demandée sans jeton', "Le garde-barrière client n'est qu'un confort : le serveur revérifie chaque appel."],
    ] },
  { t: 'pic', file: `${F}/11_enchainement.png`, w: 620,
    caption: 'Figure 6. Parcours nominal, bifurcations et états à dessiner.' },

  { t: 'h2', v: '4.4 Les quatre états de chaque écran' },
  { t: 'p', v: "Un écran n'est terminé que si ses quatre états sont dessinés. Un état oublié en maquette devient un écran blanc en production." },
  { t: 'tab',
    entetes: ['État', 'Traitement attendu'],
    largeurs: [2000, 7360], premiereGras: true,
    lignes: [
      ['Chargement', "Squelette gris aux dimensions du contenu attendu, jamais un indicateur seul qui ferait sauter la mise en page à l'arrivée des données."],
      ['Vide', "Un message qui explique, et une action pour en sortir : « Votre panier est vide, découvrir le catalogue »."],
      ['Erreur', "Message compréhensible par un client, jamais technique, toujours assorti d'une issue."],
      ['Succès', 'Notification brève, non bloquante, qui confirme sans interrompre la navigation.'],
    ] },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 5
  { t: 'h1', v: '5. Exigences de conception' },

  { t: 'h2', v: "5.1 Intention" },
  { t: 'p', v: "Le site s'adresse à des lecteurs qui savent souvent ce qu'ils cherchent : un tome précis dans une série qu'ils suivent. La priorité de conception est donc la rapidité d'accès au bon tome, avant la découverte. Tout ce qui rallonge le chemin entre l'arrivée et l'ajout au panier est un défaut." },
  { t: 'p', v: "Le second axe est la confiance : sur un catalogue d'occasion, l'acheteur doit voir immédiatement l'état du livre, sa disponibilité réelle et le prix final." },

  { t: 'h2', v: '5.2 Exigences non négociables' },
  { t: 'ul', v: [
    "Responsive : chaque écran doit rester utilisable à 390 pixels de large. La grille produits passe de cinq colonnes à deux, les filtres se replient, les actions principales restent atteignables au pouce.",
    "Accessibilité : contrastes vérifiés au seuil WCAG AA, structure sémantique, libellés ARIA sur tout élément interactif, navigation possible au clavier.",
    "Thème sombre : obligatoire, piloté par variables CSS, respectant par défaut la préférence du système.",
    "Sobriété : aucune bibliothèque d'interface externe, pour que le poids des pages reste maîtrisé.",
  ] },

  { t: 'h2', v: '5.3 Mise en page et points de rupture' },
  { t: 'p', v: "Trois seuils seulement. Ils correspondent aux usages réels, et non à des modèles d'appareils. Le contenu est centré, largeur maximale 1280 pixels, marges de 28 pixels, gouttière de 20 pixels." },
  { t: 'tab',
    entetes: ['Palier', 'Largeur', 'Grille', 'Règle'],
    largeurs: [1400, 1700, 1800, 4460], premiereGras: true,
    lignes: [
      ['Mobile', 'moins de 768 px', '2 colonnes', "Filtres repliés derrière un bouton. Navigation en bas d'écran. Action principale en pleine largeur."],
      ['Tablette', 'de 768 à 1200 px', '3 à 4 colonnes', 'Filtres en panneau latéral rétractable. En-tête complet, recherche visible.'],
      ['Bureau', 'plus de 1200 px', '5 colonnes', 'Filtres affichés en permanence à gauche. Contenu centré, largeur maximale 1280 px.'],
    ] },
  { t: 'p', v: "Les règles d'adaptation sont fixées écran par écran :" },
  { t: 'tab',
    entetes: ['Écran', "Règle d'adaptation"],
    largeurs: [2200, 7160], premiereGras: true,
    lignes: [
      ['Catalogue', "Les filtres passent d'un panneau latéral permanent à un bouton qui ouvre un panneau glissant."],
      ['Fiche produit', "Les deux colonnes, visuel et achat, s'empilent. Le bouton d'ajout occupe toute la largeur."],
      ['Panier', "Le récapitulatif passe sous les articles et devient collant en bas d'écran."],
      ['Paiement', "Les champs passent d'une grille à deux colonnes à une colonne unique."],
      ['Back-office', 'La navigation latérale se replie ; les tableaux défilent horizontalement plutôt que de se compresser.'],
      ['En-tête', 'La recherche se réduit à une icône ; les liens rejoignent un menu.'],
    ] },
  { t: 'pic', file: `${F}/05_mise_en_page.png`, w: 600,
    caption: "Figure 7. Points de rupture, grille et règles d'adaptation." },

  { t: 'h2', v: '5.4 Micro-décisions déjà tranchées' },
  { t: 'tab',
    entetes: ['Sujet', 'Règle'],
    largeurs: [2000, 7360], premiereGras: true,
    lignes: [
      ['Le prix', "Toujours en rose, en gras, jamais barré sans que le prix promotionnel soit à côté."],
      ['Le stock', "Affiché en nombre réel, pas en « disponible » ou « indisponible ». Un client veut savoir s'il reste 1 ou 40 exemplaires."],
      ["L'ajout au panier", "Ne quitte jamais la page. Une notification confirme, le badge du panier s'incrémente."],
      ['Les images', "Toujours au format 2:3, celui d'une couverture de livre. Une image manquante affiche un visuel de repli, jamais un cadre cassé."],
      ['Les erreurs de formulaire', "Sous le champ concerné, en rouge, avec la règle à respecter, et non un message global en haut de page."],
      ['Le bouton principal', "Un seul par écran. S'il y en a deux, c'est que l'écran fait deux choses."],
    ] },

  { t: 'h2', v: '5.5 Design system' },
  { t: 'p', v: "Toutes les couleurs, tailles, graisses, rayons et ombres sont déclarés une fois pour toutes sous forme de variables CSS, puis documentés dans un design system. Chaque couleur y figure avec son nom de variable, sa valeur hexadécimale, son usage et son contraste mesuré." },
  { t: 'p', v: "La mesure des contrastes au moment du design system, et non après l'intégration, a révélé que le rose de la charte ne tenait pas le seuil AA. Deux variantes ont donc été déclinées selon l'usage." },
  { t: 'tab',
    entetes: ['Couleur', 'Usage', 'Contraste'],
    largeurs: [2000, 5360, 2000], premiereGras: true,
    lignes: [
      ['#e03b8b', 'Rose de marque, en texte sur fond clair', '3,69:1, insuffisant'],
      ['#e03b8b', 'Rose de marque, en aplat sous texte blanc', '4,06:1, insuffisant'],
      ['#c62372', 'Retenu quand le rose est le texte', '4,90:1, conforme'],
      ['#d12d7d', 'Retenu quand le rose porte du texte blanc', '4,79:1, conforme'],
      ['#8a92a1', 'Gris secondaire du thème sombre, retenu', '5,10:1, conforme'],
    ] },
  { t: 'duo', caption: 'Figure 8. Palette documentée avec contrastes mesurés, et bibliothèque de composants.',
    files: [{ file: `${DS}/01_couleurs.png`, w: 300 }, { file: `${DS}/03_composants.png`, w: 300 }] },

  { t: 'h2', v: '5.6 Ton éditorial et messages' },
  { t: 'p', v: "Le ton est direct et sobre. Le site s'adresse à des passionnés : il n'a pas besoin d'en faire trop pour montrer qu'il connaît le sujet. On dit « vous » au client. On garde les termes japonais, shônen et seinen, sans les traduire. Pas de superlatifs commerciaux." },
  { t: 'p', v: "Les messages d'erreur suivent trois règles sans exception : dire ce qui s'est passé en français courant, dire quoi faire ensuite, et ne jamais divulguer d'information exploitable. Les formulations suivantes sont figées et doivent être identiques partout où le cas se présente." },
  { t: 'tab',
    entetes: ['Situation', "Ce qu'on écrit", "Ce qu'on n'écrit pas"],
    largeurs: [2200, 3800, 3360], premiereGras: true,
    lignes: [
      ['Connexion échouée', 'Email ou mot de passe incorrect', "Ce compte n'existe pas"],
      ['Mot de passe oublié', 'Si cet email existe, un lien vous a été envoyé', 'Aucun compte pour cet email'],
      ['Stock insuffisant', 'Quantité limitée à 3 pour ce produit (stock disponible : 3)', 'Erreur : stock inférieur à quantité'],
      ['Panier vide', 'Votre panier est vide, découvrir le catalogue', 'Aucun élément'],
      ["Commande d'un tiers", 'Commande introuvable', 'Accès refusé à cette commande'],
      ['Erreur serveur', 'Une erreur est survenue, réessayez dans un instant', 'Internal Server Error 500'],
    ] },
  { t: 'encadre', titre: 'Nommage et cohérence', lignes: [
    "Un même objet porte le même nom partout : on dit « panier », jamais « caddie » ni « cart » ; « commande », jamais « order ».",
    "Les statuts de commande sont fixés : en cours, validée, préparée, expédiée, livrée, annulée. La liste est déclarée une seule fois dans le code et l'interface la reprend telle quelle.",
    "Les prix s'écrivent à la française : « 9,35 € », virgule décimale et espace avant le symbole.",
  ] },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 6
  { t: 'h1', v: '6. Exigences de qualité' },

  { t: 'h2', v: '6.1 Accessibilité' },
  { t: 'ul', v: [
    "Contrastes conformes au niveau AA, soit 4,5:1 sur le texte courant, sur les deux thèmes.",
    "Structure sémantique : header, nav, main, section, footer, et non une division générique là où une balise existe.",
    "Tout élément interactif porte un libellé accessible et un état.",
    "Navigation possible au clavier, ordre de tabulation cohérent, indicateur de focus visible.",
    "Textes alternatifs sur les couvertures ; une image décorative reste vide plutôt que redondante.",
  ] },

  { t: 'h2', v: '6.2 Performance' },
  { t: 'ul', v: [
    "Le catalogue est paginé : jamais plus de résultats chargés que ceux affichés.",
    "Filtrage et tri exécutés par la base, pas par le navigateur.",
    "Index sur les colonnes les plus filtrées : catégorie, état, indicateurs commerciaux, statut.",
    "Couvertures servies depuis un cache local plutôt que depuis un service tiers.",
    "Ressources statiques mises en cache une semaine en production.",
  ] },

  { t: 'h2', v: '6.3 Éco-conception' },
  { t: 'ul', v: [
    "Aucune bibliothèque d'interface externe : le poids transféré reste faible.",
    "Images dimensionnées pour leur usage réel, et non redimensionnées par le navigateur.",
    "Pas de police décorative supplémentaire : une seule famille sur tout le site.",
    "Requêtes ciblées : on ne récupère que les colonnes et les lignes affichées.",
  ] },

  { t: 'h2', v: '6.4 Référencement' },
  { t: 'ul', v: [
    "Titres hiérarchisés, un seul h1 par page, structure sémantique respectée.",
    "Titre et méta-description propres à chaque page, décrivant son contenu réel.",
    "URL lisibles et stables, identifiants de produit explicites.",
    "Limite connue : le contenu des fiches étant injecté en JavaScript, un moteur qui n'exécute pas les scripts verra une page vide. Un rendu côté serveur serait nécessaire pour un référencement marchand.",
  ] },

  { t: 'h2', v: '6.5 Données personnelles' },
  { t: 'ul', v: [
    "Collecte minimale : identité, coordonnées de livraison, rien de plus.",
    "Mots de passe hachés avec bcrypt ; jetons d'email stockés sous forme d'empreinte SHA-256.",
    "Suppression de compte effective : les cascades effacent réellement panier, favoris, avis, annonces et commandes.",
    "Consentement aux cookies demandé avant tout dépôt non essentiel.",
    "Reste à produire pour une conformité complète : politique de confidentialité rédigée, registre des traitements, durées de conservation, export des données.",
  ] },
  { t: 'pic', file: `${F}/08_qualite.png`, w: 620,
    caption: 'Figure 9. Les cinq familles d\'exigences de qualité.' },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 7
  { t: 'h1', v: '7. Conception des données' },

  { t: 'h2', v: '7.1 Modèle conceptuel' },
  { t: 'p', v: "Le modèle est établi selon la méthode Merise. Six entités sont identifiées : Utilisateur, Produit, Commande, Éditeur, Série et Annonce." },
  { t: 'p', v: "Trois associations portent leurs propres données et deviendront des tables à part entière : le panier porte une quantité, l'avis porte une note et un commentaire, et la ligne de commande recopie le titre et le prix au moment de l'achat." },
  { t: 'pic', file: `${F}/15_mcd.png`, w: 620,
    caption: 'Figure 10. Modèle conceptuel de données, avec les cardinalités.' },

  { t: 'h2', v: '7.2 Schéma relationnel' },
  { t: 'p', v: "Le modèle conceptuel se traduit en dix-sept tables : chaque entité devient une table, chaque association plusieurs-à-plusieurs une table de liaison, chaque association un-à-plusieurs une clé étrangère." },
  { t: 'p', v: "Les règles de nommage sont homogènes et sans exception : tables au pluriel, colonnes en minuscules avec séparateur bas, clés étrangères suffixées par « _id », index préfixés par « idx_ », contraintes d'unicité par « uq_ »." },
  { t: 'p', v: "Le moteur retenu est InnoDB, seul à assurer à la fois le respect des clés étrangères et la gestion des transactions nécessaires au passage de commande. Le panier et les favoris ont une clé primaire composée, utilisateur et produit, afin que le doublon soit interdit par la structure et non par le code." },
  { t: 'pic', file: `${F}/16_mpd.png`, w: 620,
    caption: 'Figure 11. Schéma relationnel : dix-sept tables et quinze références.' },

  { t: 'h2', v: '7.3 Séquence critique : accès concurrent au stock' },
  { t: 'p', v: "Le passage de commande est le point le plus délicat de l'application. Deux clients qui valident au même instant alors qu'il reste un seul exemplaire peuvent tous deux passer le contrôle de stock avant qu'aucun ne l'ait décrémenté." },
  { t: 'p', v: "La règle « ne jamais survendre » impose donc d'enfermer toute l'opération dans une transaction unique, de verrouiller les lignes produit jusqu'à la validation, et de fixer l'ordre de verrouillage pour éviter les interblocages." },
  { t: 'pic', file: `${F}/17_sequence_commande.png`, w: 620,
    caption: "Figure 12. Deux commandes simultanées sur le dernier exemplaire : une seule aboutit." },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 8
  { t: 'h1', v: '8. Contraintes techniques' },

  { t: 'h2', v: '8.1 Pile technique' },
  { t: 'tab',
    entetes: ['Couche', 'Choix retenu', 'Motif'],
    largeurs: [1800, 3400, 4160], premiereGras: true,
    lignes: [
      ['Front-end', 'HTML5, CSS3, JavaScript natif', "Aucun framework ni bibliothèque d'interface externe : contrainte d'éco-conception et de maîtrise du rendu."],
      ['Back-end', 'Node.js, Express, architecture MVC', 'API REST, séparation stricte entre routes, contrôleurs et modèles.'],
      ['Données', 'MySQL 8, moteur InnoDB', 'Clés étrangères et transactions, requêtes préparées systématiques.'],
      ['Qualité', 'ESLint, Prettier, contrôle des scripts en ligne', "Analyse statique et formatage automatisés ; aucun script écrit dans une page."],
      ['Versions', 'Git, dépôt distant GitHub', "Historique versionné, secrets exclus par .gitignore, variables documentées dans .env.example."],
    ] },

  { t: 'h2', v: '8.2 Cibles à couvrir' },
  { t: 'ul', v: [
    "Navigateurs : deux dernières versions de Chrome, Firefox, Edge et Safari.",
    "Largeurs : de 390 à 1920 pixels, avec trois points de rupture, à 768 et 1200 pixels.",
    "Thèmes : clair et sombre, le thème système faisant foi par défaut.",
    "Accessibilité : contrastes AA, navigation clavier complète, lecteur d'écran.",
    "Langue : français ; libellés d'interface traduisibles, documentation technique lue en anglais.",
  ] },
  { t: 'pic', file: `${F}/14_contraintes_techniques.png`, w: 620,
    caption: 'Figure 13. Pile technique, cibles à couvrir et hors-périmètre technique.' },
  { t: 'saut' },

  // ═══════════════════════════════════════════════════ 9
  { t: 'h1', v: '9. Organisation et recette' },

  { t: 'h2', v: '9.1 Jalons' },
  { t: 'p', v: "Cinq phases, chacune livrant quelque chose d'utilisable." },
  { t: 'tab',
    entetes: ['Jalon', 'Contenu', 'Période'],
    largeurs: [2000, 5060, 2300], premiereGras: true,
    lignes: [
      ['1. Conception', "Cahier des charges, arborescence, enchaînement, wireframes, maquettes, design system, modèle de données", 'Du 05/01 au 13/02/2026'],
      ['2. Interfaces statiques', 'Pages HTML sémantiques, CSS responsive, thème sombre, accessibilité', 'Du 03/03 au 27/03/2026'],
      ["3. Base et accès aux données", "Schéma MySQL, couche d'accès, points d'entrée REST, transactions", 'Du 30/03 au 07/05/2026'],
      ['4. Fonctionnalités métier', 'Catalogue dynamique, panier, commande, annonces, authentification, back-office', 'Du 04/05 au 29/05/2026'],
      ['5. Consolidation', 'Reprise de sécurité, recette, documentation de déploiement', 'Du 01/06 au 05/06/2026'],
    ] },

  { t: 'h2', v: '9.2 Définition de « terminé »' },
  { t: 'p', v: "Une fonctionnalité n'est livrée que si les six points suivants sont vrais. Aucun n'est optionnel." },
  { t: 'tab',
    entetes: ['Critère', 'Ce qu\'il signifie'],
    largeurs: [3200, 6160], premiereGras: true,
    lignes: [
      ['Le cas nominal fonctionne', 'Le parcours attendu aboutit, avec des données réalistes.'],
      ["Les cas d'erreur sont traités", 'Chaque refus renvoie un message clair et une issue.'],
      ['Les entrées sont validées côté serveur', "Le contrôle côté client n'est qu'un confort."],
      ['Les droits sont vérifiés', "Propriété et rôle contrôlés côté serveur, pas seulement masqués dans l'interface."],
      ["L'écran tient à 390 pixels", "Le parcours aboutit sur mobile, pas seulement « ça ne casse pas »."],
      ["Le code passe l'analyse statique", 'ESLint sans erreur, formatage appliqué, aucun script en ligne.'],
    ] },

  { t: 'h2', v: "9.3 Jeu d'essai de référence" },
  { t: 'p', v: "Le passage de commande, fonctionnalité la plus représentative, est vérifié par douze cas, dont huit erreurs provoquées volontairement." },
  { t: 'tab',
    entetes: ['Cas provoqué', 'Résultat attendu'],
    largeurs: [4680, 4680],
    lignes: [
      ['Quantité supérieure au stock disponible', 'Refus, quantité disponible indiquée'],
      ['Produit en rupture ajouté au panier', 'Refus explicite, article signalé'],
      ['Validation avec un panier vide', 'Refus, code 400'],
      ['Commande lancée sans être connecté', 'Redirection vers la connexion, panier conservé'],
      ["Consultation de la commande d'un autre client", 'Introuvable, code 404'],
      ['Deux commandes simultanées sur le dernier exemplaire', 'Une seule aboutit, stock jamais négatif'],
      ['Quantité supérieure au plafond de 3 exemplaires', 'Refus, plafond rappelé'],
      ['Mot de passe figurant dans une fuite connue', "Refus à l'inscription, règle expliquée"],
      ['Onzième tentative de connexion en un quart d\'heure', 'Refus temporaire, code 429'],
      ["Accès à une route d'administration sans le rôle", 'Refus, code 403'],
      ['Identifiant de produit inexistant', 'Page introuvable avec chemins de sortie'],
      ['Parcours complet nominal, du catalogue au suivi', 'Commande créée, stock décrémenté, email envoyé'],
    ] },
  { t: 'pic', file: `${F}/09_planning_recette.png`, w: 620,
    caption: "Figure 14. Jalons, définition de « terminé » et jeu d'essai de référence." },
];
