// ============================================================
// translate.js — Système de traduction FR/EN KINKA.FR v8.0
// Couverture exhaustive — 873 strings
// ============================================================

const translations = {
    ': Sous 24 à 48 heures, notre service client confirme la prise en charge.': ': Within 24 to 48 hours, our customer service confirms processing.',
    ': Un nouvel exemplaire conforme vous est expédié en priorité, sans attendre la réception du colis retourné.': ': A correct replacement copy is shipped to you as a priority, without waiting for the returned package.',
    ': une étiquette de retour prépayée vous est fournie, il vous suffit de déposer le colis en point relais.': ': a prepaid return label is provided — simply drop the package at a relay point.',
    '"Mes commandes"': '"My orders"',
    '&copy; 2024 KINKA.FR. Tous droits réservés.': '© 2024 KINKA.FR. All rights reserved.',
    '&copy; 2025 KINKA.FR &mdash; Tous droits réservés': '© 2025 KINKA.FR — All rights reserved',
    '&copy; 2025 KINKA.FR — Tous droits réservés': '© 2025 KINKA.FR — All rights reserved',
    '(30 jours pour les membres Premium) pour nous retourner un article. Pour être accepté, le produit doit respecter strictement ces critères :': '(30 days for Premium members) to return an item. To be accepted, the product must strictly meet the following criteria:',
    '+3 000 titres en stock': '+3,000 titles in stock',
    '+50 000 lecteurs partagent leurs découvertes tous les mois': '+50,000 readers share their discoveries every month',
    ', même sur les précommandes.': ', even on pre-orders.',
    '-10% en continu sur le catalogue, y compris sur les nouveautés, précommandes et coffrets.': '-10% ongoing on the catalog, including new releases, pre-orders and box sets.',
    '-10% sur tout': '-10% on everything',
    '-10% sur tout le catalogue': '-10% on the entire catalog',
    '-15% sur tout le catalogue': '-15% on the entire catalog',
    '-5% sur l\'ensemble du catalogue.': '-5% on the entire catalog.',
    '-50% sur le': '-50% on the',
    '. Avec plus de 500 millions d\'exemplaires en circulation dans le monde, il est l\'auteur de manga le plus vendu de tous les temps. Son style graphique unique et sa capacité à créer des mondes vastes et imaginatifs ont redéfini le genre Shōnen.': '. With over 500 million copies in circulation worldwide, he is the best-selling manga author of all time. His unique art style and ability to create vast, imaginative worlds have redefined the Shōnen genre.',
    '0 manga sauvegardé': '0 saved manga',
    '0 manga trouvé': '0 manga found',
    '0 résultats': '0 results',
    '0 résultats • triés par pertinence': '0 results • sorted by relevance',
    '1. Préambule': '1. Preamble',
    '12 Avenue des Champs-Élysées': '12 Avenue des Champs-Élysées',
    '123 Rue du Manga': '123 Rue du Manga',
    '2 étapes': '2 steps',
    '2. Accès au site': '2. Site access',
    '2. Produits et disponibilité': '2. Products and availability',
    '213 notes étoilées': '213 star ratings',
    '3. Propriété intellectuelle': '3. Intellectual property',
    '4. Données personnelles': '4. Personal data',
    '4.1. Situations concernées': '4.1. Applicable situations',
    '4.2. Procédure spéciale pas à pas': '4.2. Step-by-step special procedure',
    '4.3. Vos options de compensation': '4.3. Your compensation options',
    '4.4. Cas non couverts par cette procédure': '4.4. Cases not covered by this procedure',
    '42 Rue du Manga': '42 Rue du Manga',
    '5. Responsabilité': '5. Liability',
    '7. Droit de rétractation': '7. Right of withdrawal',
    ': Sous 24 à 48 heures, notre service client confirme la prise en charge.': ': Within 24 to 48 hours, our customer service confirms processing.',
    ': Un nouvel exemplaire conforme vous est expédié en priorité, sans attendre la réception du colis retourné.': ': A correct replacement copy is shipped to you as a priority, without waiting for the returned package.',
    ': une étiquette de retour prépayée vous est fournie, il vous suffit de déposer le colis en point relais.': ': a prepaid return label is provided — simply drop the package at a relay point.',
    'ANNÉE DE PARUTION': 'PUBLICATION YEAR',
    'AVIS LECTEURS (830 VOTES VÉRIFIÉS)': 'READER REVIEWS (830 VERIFIED VOTES)',
    'Accède à ton espace lecteur en quelques secondes.': 'Access your reader space in seconds.',
    'Accès anticipé': 'Early access',
    'Accès aux fonctionnalités de base': 'Access to basic features',
    'Accès aux ventes privées Premium.': 'Access to Premium private sales.',
    'Accès bêta nouveautés': 'New releases beta access',
    'Accès démo instantané': 'Instant demo access',
    'Accès prioritaire aux coffrets et éditions limitées.': 'Priority access to box sets and limited editions.',
    'Accédez à votre espace personnel KINKA.FR': 'Access your personal KINKA.FR space',
    'Acheter le Tome 10': 'Buy Volume 10',
    'Acheter le Tome 12': 'Buy Volume 12',
    'Acheter le Tome 20': 'Buy Volume 20',
    'Acheter le Tome 37': 'Buy Volume 37',
    'Acheter le Tome 41': 'Buy Volume 41',
    'Action, amitié, dépassement de soi': 'Action, friendship, surpassing limits',
    'Activer la 2FA': 'Enable 2FA',
    'Adresse de livraison': 'Delivery address',
    'Affiner encore la recherche': 'Refine search further',
    'Ajouter au panier': 'Add to cart',
    'Ajouter aux favoris': 'Add to favorites',
    'Ajouter des photos': 'Add photos',
    'Ajouter le tome 1 au panier': 'Add volume 1 to cart',
    'Ajouter à ma wishlist': 'Add to my wishlist',
    'Ajoutez au moins 3 photos sous différents angles.': 'Add at least 3 photos from different angles.',
    'Ajoutez des photos claires': 'Add clear photos',
    'Alertes sur tes séries préférées': 'Alerts for your favorite series',
    'Annulable à tout moment depuis votre espace client.': 'Cancellable anytime from your account.',
    'Annulez à tout moment — remboursement intégral sous 14 jours': 'Cancel anytime — full refund within 14 days',
    'Appuyez sur le cœur d\'un manga pour l\'ajouter ici.': 'Tap the heart on a manga to add it here.',
    'Après 2 ans d\'entraînement, l\'équipage se reforme plus fort que jamais !': 'After 2 years of training, the crew reunites stronger than ever!',
    'Au moins 8 caractères': 'At least 8 characters',
    'Aucun favori pour l\'instant': 'No favorites yet',
    'Aucun favori pour le moment': 'No favorites yet',
    'Aucun titre dans cette catégorie pour le moment.': 'No titles in this category yet.',
    'Aucun titre disponible pour cette sélection.': 'No titles available for this selection.',
    'Aucun titre trouvé pour ce critère.': 'No titles found for this criterion.',
    'Aucun titre trouvé pour cette série.': 'No titles found for this series.',
    'Aucune nouveauté dans cette catégorie pour le moment.': 'No new releases in this category yet.',
    'Autres pépites à ne pas manquer': 'Other must-reads',
    'Autres éditeurs du marché': 'Other market publishers',
    'Aventure, action, combat et amitié pour tous les âges.': 'Adventure, action, combat and friendship for all ages.',
    'Bibliographie sélective': 'Selected bibliography',
    'Bon état': 'Good condition',
    'Bonjour, je vous contacte au sujet de...': 'Hello, I am contacting you regarding...',
    'CATÉGORIE': 'CATEGORY',
    'CHEF-D\'ŒUVRE': 'MASTERPIECE',
    'COUP DE CŒUR': 'STAFF PICK',
    'Caractéristiques': 'Details',
    'Catalogues complets disponibles sur KINKA.FR': 'Full catalogs available on KINKA.FR',
    'Catégorie': 'Category',
    'Catégorie principale': 'Main category',
    'Catégories': 'Categories',
    'Catégories de mangas': 'Manga categories',
    'Cette procédure spécifique s\'applique dans les cas suivants :': 'This specific procedure applies in the following cases:',
    'Chainsaw Man, Black Clover, Hunter x Hunter — reconnu pour sa rapidité de publication.': 'Chainsaw Man, Black Clover, Hunter x Hunter — known for fast publication.',
    'Changement d\'avis sans justificatif matériel (voir la section Conditions d\'acceptation)': 'Change of mind without material justification (see the Acceptance conditions section)',
    'Chaque manga est contrôlé manuellement par notre équipe et classé selon plusieurs niveaux (Comme neuf, Très bon état, Bon état). Les éventuels défauts visibles sont précisés dans la fiche produit.': 'Each manga is manually inspected by our team and graded across several levels (Like new, Very good, Good). Any visible defects are noted in the product listing.',
    'Chaque semaine, l\'équipe KINKA sélectionne pour vous les pépites absolues — ces titres qui nous ont touchés, bouleversés ou époustouflés. Des mangas que l\'on ne peut pas s\'empêcher de recommander.': 'Every week, the KINKA team hand-picks the absolute gems — titles that moved, shook, or blew us away. Manga we can\'t help but recommend.',
    'Chargement du synopsis…': 'Loading synopsis…',
    'Choisir la formule annuelle': 'Choose annual plan',
    'Choisir la formule mensuelle': 'Choose monthly plan',
    'Choisir une formule': 'Choose a plan',
    'Choisis un mot de passe difficile à deviner, puis confirme-le.': 'Choose a password that is hard to guess, then confirm it.',
    'Choisis un nouveau mot de passe sécurisé': 'Choose a new secure password',
    'Choisissez votre formule Premium': 'Choose your Premium plan',
    'Cible les adolescentes': 'Targets teenage girls',
    'Cible les adolescents masculins': 'Targets teenage boys',
    'Coffret découverte': 'Discovery box set',
    'Coffrets & Intégrales': 'Box Sets & Complete Series',
    'Coffrets & Intégrales - KINKA.FR': 'Box Sets & Complete Series - KINKA.FR',
    'Coffrets &amp; Intégrales': 'Box Sets & Complete Series',
    'Coffrets Intégrale': 'Complete Box Sets',
    'Collection en cours titres': 'Ongoing collection',
    'Combat 4 stratégies': 'Combat strategies',
    'Commandes livrées': 'Orders delivered',
    'Commandes, favoris, abonnement — tout ce qui compte pour votre passion manga, en un seul endroit.': 'Orders, favorites, subscription — everything that matters for your manga passion, all in one place.',
    'Commencer avec l\'offre annuelle': 'Start with the annual offer',
    'Commencer la collection': 'Start the collection',
    'Commencer la lecture': 'Start reading',
    'Comment fonctionne l\'accès anticipé aux coffrets ?': 'How does early access to box sets work?',
    'Comment modifier mes informations de compte ?': 'How do I edit my account information?',
    'Comment retourner un manga qui ne me convient pas ?': 'How do I return a manga that doesn\'t suit me?',
    'Comment ça marche': 'How it works',
    'Comment ça marche ?': 'How does it work?',
    'Comment évaluez-vous l\'état des mangas d\'occasion ?': 'How do you evaluate the condition of used manga?',
    'Communauté KINKA': 'KINKA Community',
    'Complet avec goodies et accessoires': 'Complete with goodies and accessories',
    'Compte de démonstration': 'Demo account',
    'Conditions Générales d\'Utilisation': 'Terms of Use',
    'Conditions Générales d\'Utilisation - KINKA.FR': 'Terms of Use - KINKA.FR',
    'Conditions Générales de Vente': 'Terms of Sale',
    'Conditions Générales de Vente - KINKA.FR': 'Terms of Sale - KINKA.FR',
    'Conditions de retour': 'Return conditions',
    'Confirmation de commande - KINKA.FR': 'Order confirmation - KINKA.FR',
    'Confirmation mot de passe': 'Password confirmation',
    'Confirmer le mot de passe': 'Confirm password',
    'Conformément aux dispositions légales en vigueur, le Client dispose d\'un délai de 14 jours à compter de la réception de ses produits pour exercer son droit de rétractation sans avoir à justifier de motifs ni à payer de pénalité.': 'Under current legal provisions, the Customer has 14 days from receipt of products to exercise their right of withdrawal without having to justify their reasons or pay any penalty.',
    'Conformément à la réglementation applicable en matière de protection des données, vous disposez d\'un droit d\'accès, de rectification, d\'opposition et de suppression des données vous concernant. Pour exercer ces droits, vous pouvez nous contacter via notre formulaire de contact.': 'In accordance with applicable data protection regulations, you have the right to access, correct, object to and delete your personal data. To exercise these rights, you may contact us via our contact form.',
    'Connecte-toi pour retrouver ton panier, suivre tes commandes et gérer ta wishlist de mangas.': 'Sign in to access your cart, track your orders and manage your manga wishlist.',
    'Connectez-vous': 'Sign in',
    'Conseil sécurité': 'Security tip',
    'Conseils pour vendre vite': 'Tips for a quick sale',
    'Construisez votre collection avec les meilleurs prix. Plus de 50 titres en promotion, neufs &amp; occasion.': 'Build your collection at the best prices. Over 50 titles on sale, new & used.',
    'Consulter le guide du vendeur': 'View seller guide',
    'Contactez-nous': 'Contact us',
    'Contactez-nous - KINKA.FR': 'Contact us - KINKA.FR',
    'Continuer mes achats': 'Continue shopping',
    'Coups de Cœur': 'Staff Picks',
    'Coups de Cœur - KINKA.FR': 'Staff Picks - KINKA.FR',
    'Coups de cœur': 'Staff picks',
    'Crédité immédiatement sur votre cagnotte Kinka pour une prochaine commande.': 'Immediately credited to your Kinka balance for a future order.',
    'Crédité sur votre moyen de paiement d\'origine (CB, PayPal).': 'Credited back to your original payment method (bank card, PayPal).',
    'Crée ton compte et accède à des milliers de mangas neufs et d\'occasion, des exclusivités et des offres personnalisées.': 'Create your account to access thousands of new and used manga, exclusives and personalized offers.',
    'Créer mon compte': 'Create my account',
    'Créer mon compte fidélité': 'Create my loyalty account',
    'Créer un compte': 'Create account',
    'Créer un compte - KINKA.FR': 'Create account - KINKA.FR',
    'Créez un compte pour sauvegarder vos points et obtenir des réductions sur vos prochaines commandes.': 'Create an account to save your points and get discounts on future orders.',
    'Créez votre annonce en quelques étapes simples.': 'Create your listing in a few simple steps.',
    'DE PUBLICATION': 'PUBLICATION',
    'Dans le cadre de l\'utilisation du site, l\'utilisateur peut être amené à communiquer des données personnelles. Ces informations sont nécessaires pour la gestion des commandes et la relation commerciale.': 'When using the site, users may be required to provide personal data. This information is necessary for order management and the commercial relationship.',
    'Dans le même genre': 'In the same genre',
    'Date de livraison estimée': 'Estimated delivery date',
    'Date de parution': 'Publication date',
    'Demon Slayer, 20th Century Boys — présent dans toute l\'Europe avec un catalogue varié.': 'Demon Slayer, 20th Century Boys — present throughout Europe with a varied catalog.',
    'Denji, un jeune homme endetté, devient Chainsaw Man après avoir fusionné avec son démon-chien. Action brutale et humour noir !': 'Denji, a debt-ridden young man, becomes Chainsaw Man after merging with his devil dog. Brutal action and dark humor!',
    'Depuis votre espace Client, vous pourrez mettre à jour votre adresse, vos informations de paiement ainsi que vos préférences de communication dans la section "Mon profil".': 'From your account, you can update your address, payment details and communication preferences in the "My profile" section.',
    'Dernière connexion': 'Last login',
    'Dernière mise à jour : 22 Oct - 09:42': 'Last updated: Oct 22 - 09:42',
    'Dernière mise à jour : 24 Janvier 2025': 'Last updated: January 24, 2025',
    'Dernières Nouveautés': 'Latest Releases',
    'Dernières sorties des éditeurs': 'Latest publisher releases',
    'Des icônes culturelles mondiales': 'Global cultural icons',
    'Des séries-phénomènes mondiales': 'Worldwide phenomenon series',
    'Des titres en très bon état jusqu\'à -40% du prix neuf.': 'Titles in very good condition, up to -40% off the new price.',
    'Des tomes soigneusement vérifiés et classés par état. Économisez sans compromis sur la qualité de lecture.': 'Carefully checked and graded volumes. Save without compromising your reading experience.',
    'Description détaillée': 'Detailed description',
    'Destiné aux femmes adultes': 'Targeted at adult women',
    'Destiné aux hommes adultes': 'Targeted at adult men',
    'Deux mois offerts par rapport au plan mensuel. Idéal pour les lecteurs réguliers.': 'Two months free vs. the monthly plan. Ideal for regular readers.',
    'Deux options s\'offrent à vous une fois le retour validé par nos équipes logistiques :': 'Two options are available once the return is validated by our logistics teams:',
    'Disponible dès maintenant.': 'Available now.',
    'Dès 4,99 €/mois · Résiliable à tout moment': 'From €4.99/month · Cancel anytime',
    'Dès 4,99&nbsp;€/mois · Résiliable à tout moment': 'From €4.99/month · Cancel anytime',
    'Dès l\'expédition de votre commande, vous recevrez un e-mail avec un lien de suivi. Vous pouvez également retrouver ce lien depuis la section "Suivi de commande" de votre compte Kinka, accessible à tout moment.': 'As soon as your order ships, you\'ll receive an email with a tracking link. You can also find this link in the "Order tracking" section of your Kinka account, accessible at any time.',
    'Début de carrière': 'Career start',
    'Déclarez votre retour dans "Mes Commandes"': 'Report your return in "My Orders"',
    'Découvrez les derniers tomes de la série phénomène de Tatsuki Fujimoto.': 'Discover the latest volumes of Tatsuki Fujimoto\'s phenomenon series.',
    'Découvrez les illustrations couleur d\'Eiichiro Oda dans ces magnifiques artbooks !': 'Discover Eiichiro Oda\'s color illustrations in these magnificent artbooks!',
    'Découvrez notre sélection de mangas neufs et d\'occasion': 'Discover our selection of new and used manga',
    'Découvrir Premium': 'Discover Premium',
    'Découvrir le Seinen': 'Explore Seinen',
    'Découvrir le catalogue': 'Explore the catalog',
    'Découvrir les éditions collectors': 'Discover collector editions',
    'Décrivez l\'état de votre manga, les éventuels défauts, pourquoi vous le vendez...': 'Describe the condition of your manga, any defects, why you\'re selling it...',
    'Défauts importants liés au transport (coffret abîmés, couverture fortement pliée)': 'Significant transport damage (damaged box set, heavily bent cover)',
    'Définir ton nouveau mot de passe': 'Set your new password',
    'Déjà membre ?': 'Already a member?',
    'Délai bancaire : 3 à 5 jours ouvrés': 'Bank processing time: 3 to 5 business days',
    'Dépensé': 'Spent',
    'Déposez le colis en point relais gratuitement': 'Drop off the package at a relay point for free',
    'Détails de la commande': 'Order details',
    'EDITION FRANÇAISE': 'FRENCH EDITION',
    'Eiichirō Oda (尾田 栄一郎) est un mangaka japonais connu pour être l\'auteur du manga': 'Eiichirō Oda (尾田 栄一郎) is a Japanese manga artist known for being the author of the manga',
    'Email + mot de passe': 'Email + password',
    'Emballage d\'expédition protecteur': 'Protective shipping packaging',
    'Embarquez pour Grand Line avec Eiichiro Oda': 'Set sail for the Grand Line with Eiichiro Oda',
    'En Stock': 'In Stock',
    'En cas de rupture de stock du produit concerné, nous vous proposons :': 'If the product is out of stock, we offer:',
    'En cliquant sur "Enregistrer", tu seras automatiquement connecté à ton compte KINKA!.FR sur cet appareil.': 'By clicking "Save", you will be automatically signed in to your KINKA.FR account on this device.',
    'En cours': 'In progress',
    'En promo': 'On sale',
    'En promotion uniquement': 'On sale only',
    'En soumettant ce formulaire, j\'accepte que mes informations soient utilisées pour traiter ma demande.': 'By submitting this form, I agree that my information will be used to process my request.',
    'En stock': 'In stock',
    'En te connectant, tu acceptes nos': 'By signing in, you agree to our',
    'En transit': 'In transit',
    'En validant votre commande, vous acceptez nos': 'By placing your order, you agree to our',
    'Enregistrer mon nouveau mot de passe': 'Save my new password',
    'Entre aliens et fantômes, l\'aventure déjantée continue de plus belle !': 'Between aliens and ghosts, the wild adventure continues stronger than ever!',
    'Entrer en démo': 'Enter demo',
    'Envoyer le lien de réinitialisation': 'Send reset link',
    'Envoyer le message': 'Send message',
    'Erreur de commande ou produit défectueux': 'Order error or defective product',
    'Espionnage, humour et tendresse au rendez-vous.': 'Espionage, humor and warmth await.',
    'Explorer le catalogue': 'Explore catalog',
    'Explorez les catalogues de vos éditeurs préférés — dernières sorties, coffrets exclusifs et classiques du manga.': 'Explore your favorite publishers\' catalogs — latest releases, exclusive box sets and manga classics.',
    'Explorez les univers qui te correspondent': 'Explore the worlds that suit you',
    'Expédition suivie 48h': '48h tracked delivery',
    'Expédiée': 'Shipped',
    'Filtrer par série :': 'Filter by series:',
    'Fixez un prix juste par rapport au marché de l\'occasion.': 'Set a fair price relative to the used market.',
    'Fondée en 1969': 'Founded in 1969',
    'Fondée en 1993': 'Founded in 1993',
    'Fondée en 1994': 'Founded in 1994',
    'Fondée en 1996': 'Founded in 1996',
    'Fondée en 2006': 'Founded in 2006',
    'Fondée en 2007': 'Founded in 2007',
    'Fondée en 2011': 'Founded in 2011',
    'Fondée en —': 'Founded: —',
    'Force du mot de passe : Moyenne': 'Password strength: Medium',
    'Format JPG ou PNG - Maximum 5 photos': 'JPG or PNG format - Maximum 5 photos',
    'Formulaire de contact': 'Contact form',
    'Genre le plus vendu au Japon': 'Best-selling genre in Japan',
    'Glenat - Tomes 1 à 12': 'Glénat - Volumes 1 to 12',
    'Glenat - Tomes 13 à 61': 'Glénat - Volumes 13 to 61',
    'Glenat - Tomes 61 à 113': 'Glénat - Volumes 61 to 113',
    'Glissez-déposez vos fichiers ici ou cliquez pour parcourir': 'Drag and drop files here or click to browse',
    'Glénat': 'Glénat',
    'Glénat Manga': 'Glénat Manga',
    'Guides & encyclopédies': 'Guides & encyclopedias',
    'Guides et encyclopédies': 'Guides and encyclopedias',
    'Guts poursuit sa quête de vengeance dans ce tome sombre et captivant.': 'Guts continues his quest for vengeance in this dark and gripping volume.',
    'Gérez votre abonnement et vos avantages': 'Manage your subscription and benefits',
    'Gérez votre formule et vos avantages': 'Manage your plan and benefits',
    'Gérez votre profil et vos coordonnées': 'Manage your profile and details',
    'Heureux de te revoir sur KINKA.FR': 'Welcome back to KINKA.FR',
    'Histoires matures, psychologiques et réalistes.': 'Mature, psychological and realistic stories.',
    'Histoires matures, émotions et tranches de vie pour adultes.': 'Mature stories, emotions and slice-of-life for adults.',
    'Historique et suivi de vos achats': 'Order history and tracking',
    'Ichigo Kurosaki devient Shinigami pour protéger les vivants et guider les âmes. Un classique du shonen d\'action surnaturel !': 'Ichigo Kurosaki becomes a Soul Reaper to protect the living and guide souls. A classic supernatural action shōnen!',
    'Identification du manga': 'Manga identification',
    'Identité': 'Identity',
    'Idéal pour découvrir Kinka Premium et tester les avantages sans engagement.': 'Ideal for discovering Kinka Premium and testing the benefits with no commitment.',
    'Immédiat + Bonus de 5%': 'Instant + 5% Bonus',
    'Imprimez l\'étiquette et préparez le colis': 'Print the label and prepare the package',
    'Inclure une lettre majuscule et un chiffre': 'Include an uppercase letter and a number',
    'Indépendant': 'Independent',
    'J\'accepte les': 'I accept the',
    'Jujutsu Kaisen, My Hero Academia, Golden Kamuy — l\'éditeur des phénomènes manga actuels.': 'Jujutsu Kaisen, My Hero Academia, Golden Kamuy — the publisher of today\'s manga phenomena.',
    'Jusqu\'à ': 'Up to ',
    'Jusqu\'à&nbsp;': 'Up to&nbsp;',
    'KINKA.FR - Votre boutique manga de référence': 'KINKA.FR - Your ultimate manga store',
    'Kazé Manga': 'Kazé Manga',
    'Ki-oon - Relié': 'Ki-oon - Hardcover',
    'Kinka Premium — Votre passeport manga — KINKA.FR': 'Kinka Premium — Your manga passport — KINKA.FR',
    'Kinka ne pourra être tenu responsable des conséquences dues à un retard d\'acheminement et n\'étant pas de son fait.': 'Kinka shall not be held responsible for consequences arising from delivery delays not attributable to Kinka.',
    'Kinka se réserve le droit de modifier ses prix à tout moment, mais le produit sera facturé sur la base du tarif en vigueur au moment de la validation de la commande.': 'Kinka reserves the right to change its prices at any time, but products will be billed at the price in effect at the time the order is confirmed.',
    'L\'Attaque des Titans, Blue Lock, Sailor Moon — l\'un des pionniers du manga en France.': 'Attack on Titan, Blue Lock, Sailor Moon — one of the pioneers of manga in France.',
    'L\'abonnement Premium vous donne accès à la livraison offerte dès un certain montant, des réductions exclusives, un accès anticipé aux coffrets limités et des bonus de fidélité sur chaque commande.': 'The Premium subscription gives you free shipping from a certain amount, exclusive discounts, early access to limited box sets and loyalty bonuses on every order.',
    'L\'accès au site Kinka.fr est gratuit. Les frais d\'accès et d\'utilisation du réseau de télécommunication sont à la charge de l\'utilisateur, selon les modalités fixées par ses fournisseurs d\'accès et opérateurs de télécommunication.': 'Access to the Kinka.fr site is free. Network access and usage costs are the responsibility of the user, per their internet service provider and telecom operator terms.',
    'L\'éditeur ne saurait être tenu responsable d\'une impossibilité d\'accès au site imputable à un cas de force majeure, à des problèmes techniques ou à des opérations de maintenance.': 'The publisher cannot be held responsible for any inability to access the site due to force majeure, technical problems or maintenance operations.',
    'L\'éditeur se réserve le droit de les corriger, dès que ces erreurs sont portées à sa connaissance. Les informations et/ou documents disponibles sur ce site sont susceptibles d\'être modifiés à tout moment, et peuvent avoir fait l\'objet de mises à jour.': 'The publisher reserves the right to correct them as soon as such errors are brought to its attention. Information and/or documents available on this site may be modified at any time and may have been updated.',
    'L\'équipage entre dans Grand Line et découvre les dangers du Nouveau Monde !': 'The crew enters the Grand Line and discovers the dangers of the New World!',
    'La bataille contre Sukuna atteint son paroxysme dans ce tome explosif !': 'The battle against Sukuna reaches its peak in this explosive volume!',
    'La confirmation de la commande entraîne acceptation des présentes CGV et forme le contrat.': 'Order confirmation constitutes acceptance of these Terms of Sale and forms the contract.',
    'La famille la plus déjantée du manga est de retour.': 'The most hilarious manga family is back.',
    'La page que vous cherchez n\'existe pas, a été déplacée ou a peut-être décidé de partir en aventure vers un autre arc narratif…': 'The page you\'re looking for doesn\'t exist, has been moved or may have decided to embark on its own story arc…',
    'La remise Premium s\'applique sur la quasi-totalité du catalogue Kinka. Certains produits très limités peuvent être exclus, cela est toujours indiqué sur la fiche produit.': 'The Premium discount applies to the vast majority of the Kinka catalog. Certain very limited products may be excluded, which is always indicated on the product page.',
    'La saisie de l\'ISBN permet de pré-remplir la fiche produit.': 'Entering the ISBN auto-fills the product sheet.',
    'La structure générale du site Kinka.fr, ainsi que les textes, graphiques, images, sons et vidéos la composant, sont la propriété de l\'éditeur ou de ses partenaires. Toute représentation et/ou reproduction et/ou exploitation partielle ou totale des contenus et services proposés par le site, par quelque procédé que ce soit, sans l\'autorisation préalable et par écrit de Kinka.fr est strictement interdite et serait susceptible de constituer une contrefaçon au sens du Code de la propriété intellectuelle.': 'The general structure of the Kinka.fr site, as well as all texts, graphics, images, sounds and videos composing it, are the property of the publisher or its partners. Any reproduction or exploitation of the site\'s content without prior written authorization from Kinka.fr is strictly prohibited and may constitute copyright infringement.',
    'Le Client peut passer commande sur le site Internet 24h/24 et 7j/7. Le processus de commande comprend les étapes suivantes : sélection des produits, validation du panier, identification ou création de compte, choix du mode de livraison, choix du mode de paiement et validation finale.': 'Customers may place orders on the website 24/7. The ordering process includes: product selection, cart validation, account login or creation, choice of delivery method, choice of payment method and final confirmation.',
    'Le cadeau d\'anniversaire, comment ça marche ?': 'How does the birthday gift work?',
    'Le combat final contre Muzan arrive à son apogée !': 'The final battle against Muzan reaches its peak!',
    'Le début d\'une aventure épique entre exorcisme et combats spectaculaires...': 'The beginning of an epic adventure between exorcism and spectacular battles...',
    'Le début de l\'aventure de Luffy qui rêve de devenir le Roi des Pirates !': 'The beginning of Luffy\'s adventure as he dreams of becoming King of the Pirates!',
    'Le josei traite des relations, de la vie professionnelle et sentimentale des femmes adultes avec une profondeur et une honnêteté que peu d\'autres genres atteignent.': 'Josei deals with the relationships, professional and romantic lives of adult women with a depth and honesty few other genres achieve.',
    'Le monument du dark fantasy de Kentaro Miura.': 'The monument of dark fantasy by Kentaro Miura.',
    'Le paysage éditorial manga en France': 'The manga publishing landscape in France',
    'Le pionnier du manga en France. One Piece, Dragon Ball, Berserk — les plus grandes séries du monde.': 'The pioneer of manga in France. One Piece, Dragon Ball, Berserk — the greatest series in the world.',
    'Le règlement de vos achats s\'effectue par carte bancaire (Visa, MasterCard, Carte Bleue) ou via PayPal. Le débit de la carte est effectué au moment de la commande.': 'Payments are made by bank card (Visa, MasterCard, CB) or via PayPal. Your card is charged at the time of the order.',
    'Le seinen s\'adresse aux adultes avec des histoires profondes, complexes, souvent sombres. Des chefs-d\'œuvre visuels et narratifs qui transcendent le medium.': 'Seinen targets adults with deep, complex, often dark stories. Visual and narrative masterpieces that transcend the medium.',
    'Le shōjo explore les émotions avec une délicatesse rare. Romance, amitié, découverte de soi — ces histoires touchent les cœurs avec une sincérité absolue.': 'Shōjo explores emotions with rare delicacy. Romance, friendship, self-discovery — these stories touch hearts with absolute sincerity.',
    'Le shōnen, c\'est l\'énergie pure du manga. Aventure, combat, amitié — ces séries portent des héros qui n\'abandonnent jamais. Des histoires qui grandissent avec vous.': 'Shōnen is the pure energy of manga. Adventure, combat, friendship — these series carry heroes who never give up. Stories that grow with you.',
    'Les Maisons d\'Édition': 'Publishers',
    'Les Maisons d\'Édition - KINKA.FR': 'Publishers - KINKA.FR',
    'Les derniers tomes de l\'arc Wano et le début de la saga finale !': 'The final volumes of the Wano arc and the beginning of the final saga!',
    'Les derniers tomes disponibles immédiatement.': 'The latest volumes available immediately.',
    'Les frais de retour sont offerts en cas d\'erreur de notre part (erreur article, produit endommagé). Pour un changement d\'avis, une participation forfaitaire peut être appliquée et sera indiquée lors de la demande de retour.': 'Return shipping is free if the error was on our part (wrong item, damaged product). For a change of mind, a flat fee may apply and will be indicated when requesting the return.',
    'Les frais de retour sont-ils à ma charge ?': 'Am I responsible for return shipping costs?',
    'Les héros affrontent une menace sans précédent !': 'The heroes face an unprecedented threat!',
    'Les informations et/ou documents figurant sur ce site et/ou accessibles par ce site proviennent de sources considérées comme étant fiables. Toutefois, ces informations et/ou documents sont susceptibles de contenir des inexactitudes techniques et des erreurs typographiques.': 'Information and/or documents on or accessible through this site come from sources considered reliable. However, they may contain technical inaccuracies and typographical errors.',
    'Les lots complets ou suites de tomes se vendent mieux.': 'Complete sets or sequential volumes sell better.',
    'Les mangas les plus acclamés par la critique': 'The most critically acclaimed manga',
    'Les mangas les plus populaires du moment, plébiscités par des milliers de lecteurs.': 'The most popular manga right now, loved by thousands of readers.',
    'Les marques "Kinka" sont des marques déposées. Toute représentation et/ou reproduction et/ou exploitation partielle ou totale de ces marques, de quelque nature que ce soit, est totalement prohibée.': 'The "Kinka" trademarks are registered trademarks. Any reproduction or exploitation of these trademarks, of any nature whatsoever, is strictly prohibited.',
    'Les paiements sont sécurisés par le protocole SSL/TLS garantissant la confidentialité des informations bancaires.': 'Payments are secured by SSL/TLS protocol, guaranteeing the confidentiality of banking information.',
    'Les prix de nos produits sont indiqués en euros toutes taxes comprises (TTC), hors participation aux frais de traitement et d\'expédition.': 'Our product prices are shown in euros inclusive of all taxes (VAT included), excluding processing and shipping fees.',
    'Les produits proposés à la vente sont ceux décrits sur le site. Kinka apporte le plus grand soin dans la présentation et la description de ses produits pour satisfaire au mieux l\'information du Client.': 'The products offered for sale are those described on the site. Kinka takes great care in presenting and describing its products to best inform the Customer.',
    'Les produits sont livrés à l\'adresse de livraison indiquée au cours du processus de commande. Les délais indiqués sont des délais moyens habituels et correspondent aux délais de traitement d\'expédition auxquels il s\'ajoute le délai d\'acheminement.': 'Products are delivered to the address provided during the ordering process. Indicated times are average standard times corresponding to processing times plus transit time.',
    'Les présentes Conditions Générales d\'Utilisation (ci-après « CGU ») ont pour objet de définir les modalités et conditions dans lesquelles Kinka.fr met à la disposition de ses utilisateurs le site et les services disponibles sur le site, ainsi que la manière par laquelle l\'utilisateur accède au site et utilise ses services.': 'These Terms of Use (hereinafter "ToU") define the terms and conditions under which Kinka.fr makes the site and its services available to users, and how users access and use these services.',
    'Les présentes Conditions Générales de Vente (ci-après « CGV ») régissent les relations contractuelles entre la société Kinka.fr et toute personne effectuant un achat via le site internet Kinka.fr (ci-après « le Client »).': 'These Terms of Sale (hereinafter "ToS") govern the contractual relationship between Kinka.fr and any person making a purchase through the Kinka.fr website (hereinafter "the Customer").',
    'Les retours sont à effectuer dans leur état d\'origine et complets (emballage, accessoires, notice). Les frais de retour sont à la charge du Client.': 'Returns must be made in original condition and complete (packaging, accessories, instructions). Return shipping costs are the responsibility of the Customer.',
    'Les réductions Premium s\'appliquent-elles sur toutes les séries ?': 'Do Premium discounts apply to all series?',
    'Les situations suivantes ne sont pas considérées comme des produits défectueux :': 'The following situations are not considered defective products:',
    'Les toutes dernières sorties du monde manga, disponibles immédiatement. Premiers arrivés, premiers servis.': 'The very latest manga releases, available immediately. First come, first served.',
    'Livraison estimée :': 'Estimated delivery:',
    'Livraison gratuite dès 50€': 'Free delivery from €50',
    'Livraison gratuite dès 50€ d\'achat': 'Free delivery from €50',
    'Livraison offerte dès 15€': 'Free shipping from €15',
    'Livraison offerte, remises exclusives et accès anticipé aux': 'Free shipping, exclusive discounts and early access to',
    'Livraison offerte, remises exclusives et accès anticipé aux coffrets collectors.': 'Free shipping, exclusive discounts and early access to collector box sets.',
    'Livraison standard offerte sur tout le site.': 'Standard shipping free on the entire site.',
    'Livrée': 'Delivered',
    'Logo Glénat': 'Glénat logo',
    'Luffy et ses compagnons continuent leur aventure au pays des Wa. La bataille d\'Onigashima atteint son paroxysme ! Alors que les combats font rage aux quatre coins de l\'île, le capitaine au chapeau de paille fait face à l\'empereur Kaido dans un duel qui déterminera le sort du pays tout entier. De nouvelles techniques, des révélations sur le passé et une détermination sans faille seront nécessaires pour venir à bout de la créature la plus forte du monde.': 'Luffy and his crew continue their adventure in Wano Country. The Battle of Onigashima reaches its peak! As fights rage across the island, the Straw Hat captain faces Emperor Kaido in a duel that will determine the fate of the entire country. New techniques, past revelations and unwavering determination will be needed to defeat the world\'s strongest creature.',
    'Légères traces d\'usure, contenu parfait.': 'Slight signs of wear, content perfect.',
    'Maison d\'édition - KINKA.FR': 'Publisher - KINKA.FR',
    'Maisons d\'édition': 'Publishers',
    'Maisons d\'édition manga': 'Manga publishers',
    'Manga d\'occasion dans un état non conforme à la description de l\'annonce': 'Used manga in a condition not matching the listing description',
    'Manga ou coffret ne correspondant pas au titre / tome commandé': 'Manga or box set not matching the ordered title / volume',
    'Meilleur rapport économies / avantages': 'Best savings / benefits ratio',
    'Merci pour votre commande !': 'Thank you for your order!',
    'Mes Favoris': 'My Favorites',
    'Mes Favoris - KINKA.FR': 'My Favorites - KINKA.FR',
    'Mes commandes': 'My orders',
    'Mes favoris': 'My favorites',
    'Mes informations': 'My information',
    'Mettre à jour': 'Update',
    'Micro-rayures ou reflets purement esthétiques n\'impactent pas la lecture': 'Minor scratches or reflections that don\'t affect reading',
    'Mieux notés': 'Top rated',
    'Modes de remboursement': 'Refund methods',
    'Modifier le mot de passe': 'Change password',
    'Mon Panier': 'My Cart',
    'Mon Panier - KINKA.FR': 'My Cart - KINKA.FR',
    'Mon Profil': 'My Profile',
    'Mon Profil - KINKA.FR': 'My Profile - KINKA.FR',
    'Mon abonnement': 'My subscription',
    'Mon compte': 'My account',
    'Mon paiement a été refusé, que faire ?': 'My payment was declined, what should I do?',
    'Mon panier': 'My cart',
    'Mon profil': 'My profile',
    'Mot de passe': 'Password',
    'Mot de passe actuel': 'Current password',
    'Mot de passe et accès sécurisé': 'Password and secure access',
    'Mot de passe mis à jour': 'Password updated',
    'Mot de passe mis à jour - KINKA.FR': 'Password updated - KINKA.FR',
    'Mot de passe oublié': 'Forgot password',
    'Mot de passe oublié ?': 'Forgot password?',
    'Moyen de paiement': 'Payment method',
    'NOUVEAUTÉS': 'NEW RELEASES',
    'NUMÉRO DE SUIVI': 'TRACKING NUMBER',
    'Naruto, Dragon Ball Super, One-Punch Man — éditeur historique qui a démocratisé le manga en France.': 'Naruto, Dragon Ball Super, One-Punch Man — a historic publisher that popularized manga in France.',
    'Neuf & occasion éligibles': 'New & used eligible',
    'Nombre de pages': 'Number of pages',
    'Non activée': 'Not activated',
    'Non, avec Premium il n\'y a aucun minimum d\'achat. Même pour un seul tome à 6,90€, vous bénéficiez de la livraison offerte.': 'No, with Premium there is no minimum purchase. Even for a single volume at €6.90, you get free shipping.',
    'Nos Coups de Cœur': 'Our Staff Picks',
    'Nos livraisons suivent le délai standard en France métropolitaine sont de 48h à 72h ouvrés via Colissimo. Pour la livraison Express, comptez 24h. Nous expéditions généralement les commandes le jour même si elles sont finalisées avant 14h.': 'Standard delivery in mainland France takes 48 to 72 business hours via Colissimo. For Express delivery, allow 24h. We generally ship orders the same day if placed before 2pm.',
    'Nos offres de produits sont valables tant qu\'elles sont visibles sur le site, dans la limite des stocks disponibles. En cas d\'indisponibilité de produit après passation de votre commande, nous vous en informerons par e-mail.': 'Our product offers are valid as long as they are visible on the site, subject to available stock. If a product becomes unavailable after your order, we will notify you by email.',
    'Nos éditeurs partenaires': 'Our partner publishers',
    'Notre équipe est là pour vous aider du lundi au vendredi, de 9h à 18h.': 'Our team is here to help you Monday to Friday, 9am to 6pm.',
    'Notre équipe support est disponible du lundi au vendredi de 9h à 18h pour vous aider.': 'Our support team is available Monday to Friday from 9am to 6pm.',
    'Nous acceptons les cartes bancaires (Visa, Mastercard), les portefeuilles électroniques (Apple Pay, Google Pay) ainsi que Paypal. Tous les paiements sont sécurisés grâce à notre prestataire de paiement certifié.': 'We accept bank cards (Visa, Mastercard), digital wallets (Apple Pay, Google Pay) and PayPal. All payments are secured through our certified payment provider.',
    'Nous contacter': 'Contact us',
    'Nous travaillons sur un service de reprise et de dépôt-vente, inscrivez-vous à la newsletter pour être informé dès son lancement et connaître les modalités de rachat.': 'We\'re working on a trade-in and consignment service — sign up for the newsletter to be notified at launch.',
    'Nouveau mot de passe': 'New password',
    'Nouveau mot de passe - KINKA.FR': 'New password - KINKA.FR',
    'Nouveau sur KINKA.FR ?': 'New to KINKA.FR?',
    'Nouveau sur Kinka': 'New to Kinka',
    'Nouveautés': 'New releases',
    'Nouveautés - KINKA.FR': 'New Releases - KINKA.FR',
    'Numéro de carte': 'Card number',
    'Né le 1er janvier 1975': 'Born January 1st, 1975',
    'OFFRES EN COURS': 'CURRENT DEALS',
    'Occasion / État des mangas': 'Used / Manga condition',
    'Offres spéciales': 'Special offers',
    'Offrez-vous l\'intégrale de vos séries préférées à prix réduit.': 'Get the complete series of your favorites at a reduced price.',
    'On va t\'aider à retrouver l\'accès à ton compte': 'We\'ll help you recover access to your account',
    'One Piece - Arc actuel (112 et suivants)': 'One Piece - Current arc (112 onwards)',
    'One Piece - Color Walk 1 à 9': 'One Piece - Color Walk 1 to 9',
    'One Piece - Nouveau Monde (61 à 100)': 'One Piece - New World (61 to 100)',
    'One Piece - Saga Grandline et Pré-Gear': 'One Piece - Grand Line saga & Pre-Gear',
    'Oops, cette page s\'est évadée !': 'Oops, this page went on an adventure!',
    'Oui, si l\'état ne correspond pas à la description de l\'annonce.': 'Yes, if the condition does not match the listing description.',
    'Oui, vous cumulez vos points fidélité comme d\'habitude et pouvez les utiliser en plus de vos réductions Premium lors du paiement.': 'Yes, you accumulate loyalty points as usual and can use them on top of your Premium discounts at checkout.',
    'Oui, vous pouvez choisir la livraison en point relais partenaire lors du paiement. Les délais sont similaires à la livraison à domicile, et vous serez notifié par e-mail dès SMS dès que le colis sera disponible.': 'Yes, you can choose relay point delivery at checkout. Delivery times are similar to home delivery, and you\'ll be notified by email and SMS once the package is available.',
    'Oui. Vous pouvez résilier votre abonnement à tout moment depuis la page « Profil > Abonnement ». Les avantages restent actifs jusqu\'à la fin de la période en cours.': 'Yes. You can cancel your subscription at any time from the "Profile > Subscription" page. Benefits remain active until the end of the current period.',
    'PHÉNOMÈNE MONDIAL': 'WORLDWIDE PHENOMENON',
    'POPULARITÉ': 'POPULARITY',
    'PREMIÈRE ÉDITION FR': 'FIRST FRENCH EDITION',
    'PUBLIC RECOMMANDÉ': 'RECOMMENDED AUDIENCE',
    'Pack / Tomes à l\'unité': 'Pack / Individual volumes',
    'Paiement 100% sécurisé — SSL': '100% Secure payment — SSL',
    'Paiement sécurisé': 'Secure payment',
    'Par': 'By',
    'Par e-mail : contact@kinka.fr': 'By email: contact@kinka.fr',
    'Parcourez notre catalogue et cliquez sur ♡ pour sauvegarder vos mangas préférés ici.': 'Browse our catalog and click ♡ to save your favorite manga here.',
    'Partager avec un Machi': 'Share with a friend',
    'Passée le 21 Octobre 2025': 'Placed on October 21st, 2025',
    'Personnages complexes et nuancés': 'Complex and nuanced characters',
    'Pika Édition': 'Pika Édition',
    'Plein écran': 'Full screen',
    'Plongez dans l\'univers des exorcistes et des malédictions.': 'Dive into the world of sorcerers and curses.',
    'Plongez dans l\'univers sombre et captivant des malédictions...': 'Dive into the dark and gripping world of curses...',
    'Plus que': 'Only',
    'Politique de Retour & Remboursement': 'Return & Refund Policy',
    'Politique de Retour & Remboursement - KINKA.FR': 'Return & Refund Policy - KINKA.FR',
    'Politique de retour': 'Return policy',
    'Pour les sorties les plus attendues, nous ouvrons les précommandes Premium 24h avant le reste des clients. Vous recevrez un email et une alerte sur votre compte pour ne rien manquer.': 'For the most anticipated releases, we open Premium pre-orders 24h before other customers. You\'ll receive an email and account alert so you don\'t miss anything.',
    'Pour toute information ou question, notre service client est à votre disposition :': 'For any information or question, our customer service is at your disposal:',
    'Prix conseillé pour l\'occasion : 3-5€': 'Recommended used price: €3-5',
    'Prix de vente (€)': 'Sale price (€)',
    'Prix décroissant': 'Price: high to low',
    'Problème technique': 'Technical issue',
    'Prochainement - Édition Gold': 'Coming soon - Gold Edition',
    'Produit présentant un défaut important (pages déchirées, erreurs d\'impression, pages manquantes, reliure déficieuse)': 'Product with a major defect (torn pages, printing errors, missing pages, defective binding)',
    'Produits défectueux': 'Defective products',
    'Produits dérivés': 'Merchandise',
    'Profitez de la livraison gratuite sur toutes vos commandes en France métropolitaine, sans minimum d\'achat.': 'Enjoy free shipping on all your orders in mainland France, with no minimum purchase.',
    'Promotions en cours': 'Current deals',
    'Proposez-vous le retrait en point relais ?': 'Do you offer relay point pickup?',
    'Précédent': 'Previous',
    'Prénom': 'First name',
    'Préparée': 'Prepared',
    'Puis-je annuler mon abonnement quand je veux ?': 'Can I cancel my subscription whenever I want?',
    'Puis-je combiner Premium avec mes points fidélité ?': 'Can I combine Premium with my loyalty points?',
    'Puis-je retourner un manga d\'occasion ?': 'Can I return a used manga?',
    'Puis-je revendre mes anciens mangas sur Kinka ?': 'Can I resell my old manga on Kinka?',
    'Qté: 1': 'Qty: 1',
    'Qté: 1 • 6,90 €': 'Qty: 1 • €6.90',
    'Qté: 2 • 13,80 €': 'Qty: 2 • €13.80',
    'Quelques secondes suffisent pour rejoindre KINKA.FR': 'It only takes a few seconds to join KINKA.FR',
    'Quels moyens de paiement acceptez-vous ?': 'What payment methods do you accept?',
    'Quels sont les avantages de l\'abonnement Premium ?': 'What are the benefits of a Premium subscription?',
    'Quels sont les délais de livraison ?': 'What are the delivery times?',
    'Question fréquente': 'Frequently asked question',
    'Question sur un produit': 'Product question',
    'Questions Fréquentes': 'Frequently Asked Questions',
    'Questions Fréquentes - KINKA.FR': 'FAQ - KINKA.FR',
    'Questions fréquentes': 'Frequently asked questions',
    'Recevez les nouvelles parutions de cette maison en avant-première.': 'Get new releases from this publisher first.',
    'Recevez nos alertes sorties, promotions et exclusivités directement dans votre boîte mail.': 'Receive our release alerts, promotions and exclusives directly in your inbox.',
    'Rechercher un manga, un auteur...': 'Search for a manga, an author...',
    'Recommandé': 'Recommended',
    'Rejoignez les élèves de U.A. dans leur quête pour devenir les plus grands héros.': 'Join the students of U.A. High in their quest to become the greatest heroes.',
    'Rejoins la communauté manga': 'Join the manga community',
    'Restez informé des nouveautés': 'Stay updated on new releases',
    'Restez à jour avec les nouvelles parutions de tous nos éditeurs partenaires.': 'Stay up to date with new releases from all our partner publishers.',
    'Retour du produit concerné': 'Return the product',
    'Retour à l\'accueil': 'Back to home',
    'Retour à la connexion': 'Back to login',
    'Retour/Échange': 'Return/Exchange',
    'Retourner à l\'accueil': 'Back to home',
    'Retrouvez les integrales de vos series preferees dans des coffrets collectors. Idéal en cadeau ou pour compléter sa collection.': 'Find complete sets of your favorite series in collector box sets. Perfect as a gift or to complete your collection.',
    'Retrouvez toutes les aventures de One Piece, des premières tomes aux derniers arcs, ainsi que les one-shots, databooks et artbooks qui enrichissent l\'univers créé par Eiichiro Oda.': 'Find all One Piece adventures, from the first volumes to the latest arcs, as well as one-shots, databooks and artbooks that enrich the universe created by Eiichiro Oda.',
    'Romance, émotions et tranches de vie touchantes.': 'Romance, emotions and touching slice-of-life.',
    'Romance, émotions, tranches de vie': 'Romance, emotions, slice of life',
    'Réaliste, nuancé, pour femmes adultes': 'Realistic, nuanced, for adult women',
    'Récapitulatif': 'Order summary',
    'Réduction permanente': 'Permanent discount',
    'Réinitialisation de mot de passe - KINKA.FR': 'Password reset - KINKA.FR',
    'Réinitialiser': 'Reset',
    'Réinitialiser ton mot de passe': 'Reset your password',
    'Réservé aux abonnés annuels, vous recevrez automatiquement un goodies manga exclusif le mois de votre anniversaire. Aucune démarche de votre part !': 'Exclusive to annual subscribers — you\'ll automatically receive an exclusive manga goodie in your birthday month. No action required!',
    'Résultats de recherche pour': 'Search results for',
    'Sans engagement. Votre abonnement se gère en un clic depuis la page Profil.': 'No commitment. Manage your subscription in one click from your Profile page.',
    'Sauvegarder le brouillon': 'Save draft',
    'Se connecter': 'Sign in',
    'Se connecter - KINKA.FR': 'Sign in - KINKA.FR',
    'Se déconnecter': 'Sign out',
    'Se souvenir de moi': 'Remember me',
    'Seinen, Shôjo': 'Seinen, Shōjo',
    'Shôjo': 'Shōjo',
    'Shônen': 'Shōnen',
    'Si vous avez reçu un article ne correspondant pas votre commande ou présentant un défaut, Kinka prend en charge l\'intégralité de la procédure. Aucuns frais de retour ne sont votre charge.': 'If you received an item that doesn\'t match your order or has a defect, Kinka handles the entire procedure at no return cost to you.',
    'Signalez le problème': 'Report the issue',
    'Site du transporteur': 'Carrier website',
    'Sortie Hajime Manga Market sur PRIMUS 24/25': 'Hajime Manga Market release on PRIMUS 24/25',
    'Sous 5 jours après réception du retour': 'Within 5 days of receiving the return',
    'Soyez honnête sur l\'état (cornes, jaunissement).': 'Be honest about condition (dog ears, yellowing).',
    'Soyez prévenu en avance et commandez les éditions limitées avant la mise en vente publique.': 'Be notified in advance and order limited editions before public release.',
    'Spy × Family, Dungeon Meshi, Chihayafuru — qualité de traduction reconnue, diversité éditoriale.': 'Spy × Family, Dungeon Meshi, Chihayafuru — renowned translation quality, editorial diversity.',
    'Style graphique délicat et élégant': 'Delicate and elegant art style',
    'Suivez toutes vos commandes en temps réel': 'Track all your orders in real time',
    'Suivi de commande': 'Order tracking',
    'Suivi de commande - KINKA.FR': 'Order tracking - KINKA.FR',
    'Support client dédié Premium.': 'Dedicated Premium customer support.',
    'Supprimer mon compte': 'Delete my account',
    'Sur cette page': 'On this page',
    'Sword Art Online, Made in Abyss — spécialisé dans les light novels et mangas d\'isekai.': 'Sword Art Online, Made in Abyss — specialized in light novels and isekai manga.',
    'SÉLECTION ÉDITORIALE': 'EDITORIAL SELECTION',
    'SÉRIE CULTE': 'CULT SERIES',
    'Sécurité': 'Security',
    'Sécurité du compte': 'Account security',
    'Sécurité renforcée': 'Enhanced security',
    'Série': 'Series',
    'Série complète': 'Complete series',
    'Séries': 'Series',
    'Séries phares': 'Key series',
    'Séries suivies': 'Followed series',
    'Takemichi doit sauver ses amis dans ce tome bouleversant !': 'Takemichi must save his friends in this heartbreaking volume!',
    'Tanjiro devient pourfendeur de démons pour sauver sa sœur transformée. Une aventure épique mêlant action et émotion !': 'Tanjiro becomes a demon slayer to save his transformed sister. An epic adventure blending action and emotion!',
    'Tant le présent site que les modalités et conditions de son utilisation sont régis par le droit français, quel que soit le lieu d\'utilisation. En cas de contestation éventuelle, et après l\'échec de toute tentative de recherche d\'une solution amiable, les tribunaux français seront seuls compétents pour connaître de ce litige.': 'Both this site and the terms of its use are governed by French law, regardless of place of use. In case of dispute, after failure of any attempt to reach an amicable settlement, French courts shall have exclusive jurisdiction.',
    'Temps estimé': 'Estimated time',
    'Thèmes : amitié, persévérance, combat': 'Themes: friendship, perseverance, combat',
    'Thèmes : amour, amitié, identité': 'Themes: love, friendship, identity',
    'Thèmes : carrière, romance mature, vie quotidienne': 'Themes: career, mature romance, everyday life',
    'Thèmes : philosophie, violence, société': 'Themes: philosophy, violence, society',
    'Titre du manga': 'Manga title',
    'Titulaire de la carte': 'Cardholder name',
    'Tome 41 — édition posthume disponible.': 'Volume 41 — posthumous edition available.',
    'Tomes protégés dans des pochettes individuelles': 'Volumes protected in individual sleeves',
    'Total payé': 'Total paid',
    'Tous les genres': 'All genres',
    'Tous les guides et encyclopédies pour tout savoir sur l\'univers de One Piece !': 'All guides and encyclopedias to know everything about the One Piece universe!',
    'Tous les mangas': 'All manga',
    'Tous les tomes disponibles': 'All available volumes',
    'Tous les tomes en tant qu\'auteur': 'All volumes as author',
    'Tous les états': 'All conditions',
    'Tous nos produits bénéficient de la garantie légale de conformité et de la garantie des vices cachés, prévues par les articles 1641 et suivants du Code civil.': 'All our products benefit from the legal guarantee of conformity and the guarantee against hidden defects, under Articles 1641 et seq. of the Civil Code.',
    'Tout ce que vous devez savoir sur nos mangas, nos livraisons et nos services.': 'Everything you need to know about our manga, deliveries and services.',
    'Tout du plan Membre': 'Everything in the Member plan',
    'Tout du plan Premium': 'Everything in the Premium plan',
    'Tout savoir sur les retours, les échanges et les remboursements chez Kinka. Une procédure simple pour acheter en toute sérénité.': 'Everything about returns, exchanges and refunds at Kinka. A simple process for worry-free shopping.',
    'Toute commande passée sur le site implique l\'adhésion entière et sans réserve du Client aux présentes CGV.': 'Any order placed on the site constitutes full and unreserved acceptance of these Terms of Sale.',
    'Toute connexion au site est subordonnée au respect des présentes conditions.': 'All site access is subject to compliance with these terms.',
    'Toutes catégories': 'All categories',
    'Traits légers ou marques d\'usure sur les mangas d\'occasion (traces de lecture classiques)': 'Light marks or wear on used manga (normal reading traces)',
    'Trier : plus récent': 'Sort: newest',
    'Trier par': 'Sort by',
    'Trier par titre': 'Sort by title',
    'Très bon état': 'Very good condition',
    'Tu viens d\'ouvrir un lien sécurisé envoyé par e-mail. Pour terminer, définis un nouveau mot de passe pour ton compte KINKA!.FR.': 'You\'ve opened a secure link sent by email. To finish, set a new password for your KINKA.FR account.',
    'Télécharger la facture': 'Download invoice',
    'Téléphone': 'Phone',
    'Téléphone (pour la livraison)': 'Phone (for delivery)',
    'Un art visuel souvent exceptionnel': 'Often exceptional visual art',
    'Un ninja condamné à mort part en quête de l\'élixir d\'immortalité sur une île mystérieuse. Combats épiques et créatures terrifiantes !': 'A ninja sentenced to death seeks the elixir of immortality on a mysterious island. Epic battles and terrifying creatures!',
    'Un regard authentique sur la vie': 'An authentic look at life',
    'Un shônen d\'exorcistes spectaculaires et percutants !': 'A spectacular, hard-hitting shōnen about exorcists!',
    'Une description détaillée rassure les acheteurs.': 'A detailed description reassures buyers.',
    'Une description honnête rassure les acheteurs': 'An honest description reassures buyers',
    'Une question sur une commande ou un produit ? Notre équipe est là pour vous aider.': 'A question about an order or product? Our team is here to help.',
    'Usure visible mais lisible sans souci.': 'Visible wear but perfectly readable.',
    'Vagabond, Oyasumi Punpun, Blame! — les œuvres d\'auteurs qui ont marqué l\'histoire du manga.': 'Vagabond, Oyasumi Punpun, Blame! — works by authors who shaped manga history.',
    'Valeur estimée :': 'Estimated value:',
    'Validation par nos équipes': 'Validated by our teams',
    'Validée': 'Confirmed',
    'Vendre un manga': 'Sell a manga',
    'Vendre un manga - KINKA.FR': 'Sell a manga - KINKA.FR',
    'Via notre': 'Via our',
    'Voir la collection': 'Browse collection',
    'Voir la série complète': 'See the full series',
    'Voir le catalogue': 'Browse the catalog',
    'Voir le détail des avantages': 'See benefit details',
    'Voir les coffrets': 'Browse box sets',
    'Voir les coffrets disponibles': 'Browse available box sets',
    'Voir les nouveautés': 'See new releases',
    'Voir les occasions': 'Browse used manga',
    'Voir tous les tomes disponibles': 'See all available volumes',
    'Voir tout le dark shōnen': 'See all dark shōnen',
    'Voir toute la FAQ': 'See the full FAQ',
    'Voir toutes les nouveautés': 'See all new releases',
    'Voir toutes les offres': 'See all offers',
    'Volumes publiés': 'Published volumes',
    'Votre adresse e-mail': 'Your email address',
    'Votre boutique de référence': 'Your trusted store',
    'Votre boutique manga de confiance. Neufs, occasions, coffrets et exclusivités livrés chez vous.': 'Your trusted manga store. New, used, box sets and exclusives delivered to you.',
    'Votre boutique manga de confiance. Neufs, occasions, coffrets et exclusivités.': 'Your trusted manga store. New, used, box sets and exclusives.',
    'Votre boutique manga de confiance. Neufs, occasions, coffrets.': 'Your trusted manga store. New, used, box sets.',
    'Votre boutique manga de référence.': 'Your ultimate manga store.',
    'Votre colis est arrivé au centre de tri régional (Paris Sud).': 'Your package has arrived at the regional sorting center (Paris South).',
    'Votre commande': 'Your order',
    'Votre espace': 'Your space',
    'Votre liste de mangas enregistrés': 'Your saved manga list',
    'Votre mot de passe a été modifié avec succès. Vous pouvez maintenant vous connecter en toute sécurité à votre compte Kinka!.': 'Your password has been successfully changed. You can now sign in securely to your Kinka account.',
    'Votre passeport pour le meilleur du manga': 'Your passport to the best manga',
    'Vous aimerez aussi': 'You might also like',
    'Vous avez gagné 210 points Kinka! !': 'You earned 210 Kinka points!',
    'Vous disposez de': 'You have',
    'Vous disposez de 14 jours après réception pour demander un retour depuis votre espace client, rubrique "Mes commandes". Une étiquette de retour vous sera fournie et le remboursement sera effectué après réception et contrôle de l\'article.': 'You have 14 days after receipt to request a return from your account, under "My orders". A return label will be provided and the refund processed after receipt and inspection.',
    'Vous ne trouvez pas votre réponse ?': 'Can\'t find your answer?',
    'Vous pourriez aimer': 'You might like',
    'Vérifiez que vos informations bancaires sont correctes et que votre plafond n\'est pas atteint. Si le problème persiste, contactez votre banque puis notre support en indiquant le message d\'erreur pour que nous puissions vous aider.': 'Check that your banking details are correct and your limit hasn\'t been reached. If the problem persists, contact your bank then our support with the error message.',
    'Wishlist et historique de commandes': 'Wishlist and order history',
    'Wishlist illimitée': 'Unlimited wishlist',
    'Y a-t-il un minimum d\'achat pour la livraison gratuite ?': 'Is there a minimum purchase for free shipping?',
    'Yuji Itadori découvre le monde des malédictions et des exorcistes...': 'Yuji Itadori discovers the world of curses and sorcerers...',
    'Yuji Itadori, lycéen à la force physique hors norme, vit sa vie classique. Le jour où il avale un doigt de Ryomen Sukuna, le plus puissant des fléaux. Devenu l\'hôte de cette malédiction, il rejoint l\'école d\'exorcisme de Tokyo afin d\'apprendre les rouages reliques maudites. Humour noir, combat au combat, Jujutsu Kaisen redéfond le shônen sombre.': 'Yuji Itadori, a high schooler with extraordinary physical strength, lives an ordinary life — until the day he swallows a finger of Ryomen Sukuna, the most powerful of cursed spirits. Now the host of this curse, he joins Tokyo\'s school of sorcery to master jujutsu. Dark humor, intense battles — Jujutsu Kaisen redefines the dark shōnen.',
    'Yuji Itadori, lycéen à la force physique hors norme, vit sa vie classique...': 'Yuji Itadori, a high schooler with extraordinary physical strength, lives his ordinary life...',
    'Yûji Kaku • Dark Shonen': 'Yûji Kaku • Dark Shōnen',
    'a bien été confirmée. Un email récapitulatif a été envoyé à': 'has been confirmed. A summary email has been sent to',
    'avoir Kinka bonifié': 'bonus Kinka credit',
    'coffrets collectors. Kinka Premium accompagne votre passion au': 'collector box sets. Kinka Premium accompanies your passion at',
    'conditions générales': 'terms of service',
    'de KINKA.FR': 'from KINKA.FR',
    'de l\'article et des frais de livraison liés': 'for the item and associated shipping costs',
    'depuis votre section': 'from your section',
    'disponibles à ce prix.': 'available at this price.',
    'en promotion': 'on sale',
    'et d\'occasion en France.': 'and used manga in France.',
    'et la': 'and the',
    'et notre': 'and our',
    'formulaire de contact': 'contact form',
    'jusqu\'à -40%': 'up to -40%',
    'montrant le défaut (couverture, pages concernées, carton d\'envoi si abîmé).': 'showing the defect (cover, affected pages, shipping box if damaged).',
    'niveaux d\'état': 'condition grades',
    'ou 69,99€/an — économisez 26%': 'or €69.99/year — save 26%',
    'ou continuer avec': 'or continue with',
    'ou tester avec le compte démo': 'or test with the demo account',
    'ou via le formulaire de contact en choisissant le motif de Produit défectueux / erreur de référence.': 'or via the contact form choosing the reason Defective product / reference error.',
    'politique de confidentialité': 'privacy policy',
    'pour l\'achat de mangas neufs': 'for buying new manga',
    'préparable G': 'ready',
    'remboursement intégral': 'full refund',
    'sur le site': 'on the site',
    'sur les nouveautés et coffrets.': 'on new releases and box sets.',
    'séries disponibles': 'available series',
    'titres au catalogue': 'titles in catalog',
    'titres en stock': 'titles in stock',
    'titres sélectionnés': 'titles selected',
    'utilisable sur une prochaine commande (selon nos offres en vigueur)': 'usable on a future order (subject to current offers)',
    'votre@email.fr': 'your@email.com',
    '© 2025 KINKA.FR — Tous droits réservés': '© 2025 KINKA.FR — All rights reserved',
    'Éditeur': 'Publisher',
    'Édition collector disponible.': 'Collector edition available.',
    'Équipe support KINKA!': 'KINKA! Support Team',
    'État': 'Condition',
    'État acceptable': 'Acceptable condition',
    'État du compte': 'Account status',
    'État du manga': 'Manga condition',
    'État et Prix': 'Condition & Price',
    'État neuf, jamais lu, aucune pliure': 'New condition, never read, no creases',
    'État vérifié': 'Verified status',
    'Évite de réutiliser un mot de passe déjà utilisé sur un autre site.': 'Avoid reusing a password already used on another site.',
    'Éviter ton nom, pseudo ou adresse e-mail': 'Avoid using your name, username or email',
    'éditeurs partenaires': 'partner publishers',
    'éligible': 'eligible',
    'Accueil': 'Home',
    'Catalogue': 'Catalog',
    'Promotions': 'Deals',
    'Coffrets': 'Box Sets',
    'Connexion': 'Login',
    'Inscription': 'Sign up',
    'Tous droits réservés': 'All rights reserved',
    'Meilleures Ventes': 'Best Sellers',
    'Meilleures ventes': 'Best sellers',
    'Voir tout': 'See all',
    'Acheter': 'Buy',
    'Valider': 'Confirm',
    'Annuler': 'Cancel',
    'Retour': 'Back',
    'Fermer': 'Close',
    'Modifier': 'Edit',
    'Supprimer': 'Delete',
    'Enregistrer': 'Save',
    'S\'abonner': 'Subscribe',
    'S\'inscrire': 'Sign up',
    'Filtrer': 'Filter',
    'Trier': 'Sort',
    'Pertinence': 'Relevance',
    'Prix croissant': 'Price: low to high',
    'Meilleures notes': 'Best rated',
    'Utiliser': 'Use',
    'Tout le catalogue': 'Full catalog',
    'Toutes': 'All',
    'Tout': 'All',
    'Occasion': 'Used',
    'Neuf': 'New',
    'Coffret': 'Box Set',
    'Filtres': 'Filters',
    'En promotion': 'On sale',
    'Prix': 'Price',
    'résultats': 'results',
    'Fondée en': 'Founded in',
    'titres chez KINKA': 'titles at KINKA',
    'Site officiel': 'Official website',
    'Alertes sorties': 'Release alerts',
    'Auteur': 'Author',
    'Genre': 'Genre',
    'Note': 'Rating',
    'Rupture de stock': 'Out of stock',
    'Description': 'Description',
    'Informations': 'Information',
    'Tome': 'Volume',
    'Pages': 'Pages',
    'Format': 'Format',
    'Langue': 'Language',
    'Français': 'French',
    'Produits similaires': 'Similar products',
    'Votre panier': 'Your cart',
    'Sous-total': 'Subtotal',
    'Livraison': 'Shipping',
    'Total': 'Total',
    'Passer la commande': 'Place order',
    'Continuer les achats': 'Continue shopping',
    'Votre panier est vide': 'Your cart is empty',
    'Commencer à magasiner': 'Start shopping',
    'Quantité': 'Quantity',
    'Adresse e-mail': 'Email address',
    'Abonnement': 'Subscription',
    'Déconnexion': 'Logout',
    'Membre': 'Member',
    'Commandes': 'Orders',
    'Favoris': 'Favorites',
    'Membre depuis': 'Member since',
    'Informations personnelles': 'Personal information',
    'Historique des commandes': 'Order history',
    'Réduction': 'Discount',
    'Prix réduit': 'Sale price',
    'Prix original': 'Original price',
    'manga sauvegardé': 'saved manga',
    'mangas sauvegardés': 'saved manga',
    'Parcourez notre catalogue et ajoutez vos mangas préférés en cliquant sur ♡': 'Browse our catalog and add your favorite manga by clicking ♡',
    'Tout effacer': 'Clear all',
    'A–Z': 'A–Z',
    'Z–A': 'Z–A',
    'Paiement': 'Checkout',
    'Code promo': 'Promo code',
    'Appliquer': 'Apply',
    'Carte Bancaire': 'Credit Card',
    'Date d\'expiration': 'Expiry date',
    'Expiration': 'Expiry',
    'Informations de livraison': 'Delivery information',
    'Méthode de paiement': 'Payment method',
    'Votre panier est vide.': 'Your cart is empty.',
    'Nom': 'Last name',
    'Adresse': 'Address',
    'Code Postal': 'Zip code',
    'Code postal': 'Zip code',
    'Ville': 'City',
    'Visa, Mastercard, CB': 'Visa, Mastercard',
    'Payer': 'Pay',
    'Informations enregistrées': 'Information saved',
    'Modifications annulées': 'Changes cancelled',
    'Se déconnecter ?': 'Sign out?',
    'Supprimer définitivement votre compte ?': 'Permanently delete your account?',
    'Compte supprimé': 'Account deleted',
    'Non connecté': 'Not logged in',
    'Bientôt disponible : 2FA': 'Coming soon: 2FA',
    'Plan actuel': 'Current plan',
    'Accès bêta': 'Beta access',
    'Annulée': 'Cancelled',
    'Historique commandes': 'Order history',
    'Sauvegardez vos mangas favoris': 'Save your favorite manga',
    'Catalogue complet': 'Full catalog',
    'Collector': 'Collector',
    'Premium': 'Premium',
    'Retours': 'Returns',
    'Annuel': 'Annual',
    'Artbooks': 'Artbooks',
    'Aucune marque visible. Comme neuf.': 'No visible marks. Like new.',
    'Besoin d\'aide ?': 'Need help?',
    'Bons plans': 'Deals',
    'Chargement…': 'Loading…',
    'Colissimo': 'Colissimo',
    'Collection': 'Collection',
    'Comme neuf': 'Like new',
    'Confirmation commande': 'Order confirmation',
    'Contact': 'Contact',
    'Disponibles': 'Available',
    'Dès 4,99 €/mois · Résiliable à tout moment': 'From €4.99/month · Cancel anytime',
    'Email': 'Email',
    'Formule souple': 'Flexible plan',
    'Guides & databooks': 'Guides & databooks',
    'Info Transporteur': 'Carrier info',
    'JOSEI': 'JOSEI',
    'Lien valide encore 25 minutes': 'Link valid for 25 more minutes',
    'MAGAZINE D\'ORIGINE': 'SOURCE MAGAZINE',
    'Mensuel': 'Monthly',
    'Message': 'Message',
    'Moins d\'1 min': 'Under 1 min',
    'Note moyenne': 'Average rating',
    'Photos': 'Photos',
    'Remises permanentes': 'Permanent discounts',
    'STATUT': 'STATUS',
    'SYNOPSIS': 'SYNOPSIS',
    'Sous blister': 'Shrink-wrapped',
    'Standard Domicile': 'Home delivery',
    'Suivi commande': 'Order tracking',
    'Suivre l\'auteur': 'Follow the author',
    'Suivre ma commande': 'Track my order',
    'Sujet': 'Subject',
    'Traces d\'usure': 'Signs of wear',
    'VOLUMES DISPONIBLES': 'AVAILABLE VOLUMES',
    'Ventes flash': 'Flash sales',
    'Ventes flash exclusives': 'Exclusive flash sales',
    'Vos avantages inclus': 'Your included benefits',
    'Zone dangereuse': 'Danger zone',
    'economies max': 'maximum savings',
    'Ajouté aux favoris': 'Added to favorites',
    'Ajouté aux favoris !': 'Added to favorites!',
    'Ajouté au panier !': 'Added to cart!',
    'Retiré des favoris': 'Removed from favorites',
    'Produit retiré du panier': 'Product removed from cart',
    'Identifiants démo remplis [ok]': 'Demo credentials filled [ok]',
    'Inscription confirmée [ok]': 'Subscription confirmed [ok]',
    'Total TTC': 'Total (incl. tax)',
    'Gratuite': 'Free',
    'Gratuit': 'Free',
    'Commander': 'Place order',
    'Récapitulatif de commande': 'Order summary',
    'article': 'item',
    'articles': 'items',
    'Augmenter': 'Increase',
    'Diminuer': 'Decrease',
    'pour la livraison gratuite !': 'left for free shipping!',
    'Retirer': 'Remove',
    'Qté': 'Qty',
    'Qté :': 'Qty:',
    'Votre nom': 'Your name',
    'Votre email': 'Your email',
    'Votre message': 'Your message',
    'Commande en cours': 'Order in progress',
    'En préparation': 'Processing',
    'Numéro de commande': 'Order number',
    'Commande confirmée': 'Order confirmed',
    'Merci pour votre commande': 'Thank you for your order',
    'Shōnen': 'Shōnen',
    'Shōjo': 'Shōjo',
    'Josei': 'Josei',
    'Seinen': 'Seinen',
    'Mature, psychologique, sans compromis': 'Mature, psychological, uncompromising',
    'Catalogue Manga': 'Manga Catalog',
    'En bref': 'In brief',
    'Pourquoi on adore :': 'Why we love it:',
    'L\'équipe KINKA': 'The KINKA team',
    'Libraires passionnés': 'Passionate booksellers',
    'note moyenne': 'average rating',
    'libraires experts': 'expert booksellers',
    'Livraison Standard': 'Standard Shipping',
    'Livraison express offerte': 'Express shipping included',
    'Livraison gratuite': 'Free shipping',
    'Livraison gratuite sans min.': 'Free shipping, no minimum.',
    'Livraison offerte': 'Free shipping',
    'Payer —': 'Pay —',
    'Kinka Premium': 'Kinka Premium',
    'Support prioritaire': 'Priority support',
    'Offres exclusives membres': 'Exclusive member offers',
    'Coffret surprise mensuel': 'Monthly mystery box',
    'Double authentification': 'Two-factor authentication',
    'Badge Collector exclusif': 'Exclusive Collector badge',
    'Cumulable Premium': 'Stackable with Premium',
    'Cadeau d\'anniversaire (goodies manga exclusifs).': 'Birthday gift (exclusive manga goodies).',
    'CONNEXION': 'LOGIN',
    'Authentification': 'Authentication',
    'Retours sous 30 jours': '30-day returns',
    'NOUVEAU': 'NEW',
    'BEST-SELLER': 'BEST-SELLER',
    'OCCASION': 'USED',
    'PROMO': 'SALE',
    'Tout voir': 'View all',
};


// ============================================================
// ÉTAT
// ============================================================
let currentLang = localStorage.getItem('kinka_lang') || 'fr';

// Cache de lookup normalisé pour éviter les faux manquements dus aux espaces
let _normIndex = null;
function getNormIndex() {
    if (_normIndex) return _normIndex;
    _normIndex = new Map();
    for (const [fr] of Object.entries(translations)) {
        _normIndex.set(fr.trim().replace(/\s+/g, ' '), fr);
    }
    return _normIndex;
}

function translateText(txt) {
    if (!txt) return null;
    // Exact match
    if (translations[txt]) return translations[txt];
    // Normalized match (trim + collapse whitespace)
    const norm = txt.trim().replace(/\s+/g, ' ');
    if (translations[norm]) return translations[norm];
    const origKey = getNormIndex().get(norm);
    if (origKey) return translations[origKey];
    return null;
}

// ============================================================
// MOTEUR DE TRADUCTION
// ============================================================
function applyTranslations(lang) {
    if (lang === 'fr') { location.reload(); return; }

    // 1. Attributs data-i18n (priorité absolue)
    document.querySelectorAll('[data-i18n]').forEach(function(el) {
        const tr = translateText(el.getAttribute('data-i18n'));
        if (tr) el.textContent = tr;
    });

    // 2. Attributs placeholder / title / alt / aria-label
    document.querySelectorAll('[placeholder],[title],[alt],[aria-label]').forEach(function(el) {
        ['placeholder', 'title', 'alt', 'aria-label'].forEach(function(attr) {
            if (el.hasAttribute(attr)) {
                const tr = translateText(el.getAttribute(attr));
                if (tr) el.setAttribute(attr, tr);
            }
        });
    });

    // 3. Walker sur tous les nœuds texte du DOM
    walkNode(document.body);

    // 4. Titre de la page
    const titleTr = translateText(document.title) || translateText(document.title.split(' - ')[0]);
    if (titleTr) document.title = titleTr;
}

function walkNode(node) {
    if (!node) return;
    if (node.nodeType === Node.TEXT_NODE) {
        const raw = node.textContent;
        if (!raw || !raw.trim()) return;
        const tr = translateText(raw.trim());
        if (tr) {
            // Préserver les espaces de début/fin
            const lead = raw.match(/^\s*/)[0];
            const trail = raw.match(/\s*$/)[0];
            node.textContent = lead + tr + trail;
        }
    } else if (node.nodeType === Node.ELEMENT_NODE) {
        const tag = node.tagName;
        if (tag === 'SCRIPT' || tag === 'STYLE' || tag === 'CODE' || tag === 'PRE') return;
        if (node.id === 'translate-toggle') return;
        node.childNodes.forEach(walkNode);
    }
}

// ============================================================
// BOUTON TRANSLATE
// ============================================================
function injectTranslateBtn() {
    const anchor = document.querySelector('.connect-btn') || document.querySelector('.nav-user-wrap');
    if (!anchor || document.getElementById('translate-toggle')) return;

    const btn = document.createElement('button');
    btn.id = 'translate-toggle';
    btn.className = 'icon-btn';
    btn.title = currentLang === 'fr' ? 'Switch to English' : 'Passer en français';
    btn.setAttribute('aria-label', btn.title);
    btn.innerHTML = `<span style="font-size:.75rem;font-weight:700;letter-spacing:.04em">${currentLang === 'fr' ? 'EN' : 'FR'}</span>`;

    btn.addEventListener('click', function() {
        if (currentLang === 'fr') {
            currentLang = 'en';
            localStorage.setItem('kinka_lang', 'en');
            btn.innerHTML = '<span style="font-size:.75rem;font-weight:700;letter-spacing:.04em">FR</span>';
            btn.title = 'Passer en français';
            btn.setAttribute('aria-label', btn.title);
            applyTranslations('en');
            startMutationObserver();
        } else {
            currentLang = 'fr';
            localStorage.setItem('kinka_lang', 'fr');
            applyTranslations('fr');
        }
    });

    anchor.parentNode.insertBefore(btn, anchor);
}

// ============================================================
// EXPOSITION GLOBALE (appelé après chaque renderGrid)
// ============================================================
window.kinka_translate = function() {
    if (currentLang === 'en') applyTranslations('en');
};

// ============================================================
// MUTATION OBSERVER — traduit les nœuds injectés dynamiquement
// ============================================================
let _observerStarted = false;
function startMutationObserver() {
    if (_observerStarted || currentLang !== 'en' || !window.MutationObserver) return;
    _observerStarted = true;
    let debounce = null;
    const obs = new MutationObserver(function(mutations) {
        const hasNew = mutations.some(m => m.addedNodes.length > 0);
        if (!hasNew) return;
        clearTimeout(debounce);
        debounce = setTimeout(function() {
            mutations.forEach(function(m) {
                m.addedNodes.forEach(function(n) { walkNode(n); });
            });
        }, 60);
    });
    obs.observe(document.body, { childList: true, subtree: true });
}

// ============================================================
// INIT
// ============================================================
(function() {
    function init() {
        injectTranslateBtn();
        if (currentLang === 'en') {
            applyTranslations('en');
            startMutationObserver();
        }
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
